import 'package:flutter/material.dart';
import '../models/article.dart';
import '../models/category.dart';
import '../models/user.dart';
import '../models/comment.dart';
import '../models/notification.dart';

class MockData {
  static final List<Category> categories = [
    Category(id: 'all', name: 'All', icon: Icons.public, color: '#1E88E5', articleCount: 30),
    Category(id: 'politics', name: 'Politics', icon: Icons.account_balance, color: '#E53935', articleCount: 5),
    Category(id: 'sports', name: 'Sports', icon: Icons.sports_soccer, color: '#43A047', articleCount: 5),
    Category(id: 'tech', name: 'Technology', icon: Icons.computer, color: '#8E24AA', articleCount: 5),
    Category(id: 'entertainment', name: 'Entertainment', icon: Icons.movie, color: '#FB8C00', articleCount: 4),
    Category(id: 'business', name: 'Business', icon: Icons.business_center, color: '#00897B', articleCount: 4),
    Category(id: 'health', name: 'Health', icon: Icons.health_and_safety, color: '#D81B60', articleCount: 4),
    Category(id: 'science', name: 'Science', icon: Icons.science, color: '#3949AB', articleCount: 3),
  ];

  static const String _loremContent = '''
In a rapidly evolving world, developments continue to shape our daily lives in unprecedented ways. Experts and analysts have been closely monitoring the situation, providing insights that help us understand the broader implications of these changes.

According to recent reports, the impact has been significant across multiple sectors. Industry leaders have expressed both optimism and caution, emphasizing the need for balanced approaches to navigate these complex dynamics.

"We are at a pivotal moment," said Dr. Sarah Chen, a leading researcher in the field. "The decisions we make today will have lasting consequences for generations to come. It's crucial that we approach this with both urgency and thoughtfulness."

The data suggests a clear trend toward transformation. Statistics from the latest quarter show remarkable shifts in consumer behavior, technological adoption, and policy frameworks. These changes are not isolated to any single region but represent a global phenomenon that requires coordinated responses.

Community stakeholders have begun organizing forums and workshops to address the most pressing concerns. Local leaders are working alongside national agencies to develop comprehensive strategies that balance economic growth with social responsibility.

As the situation continues to develop, observers note that adaptability and innovation will be key factors in determining outcomes. The coming months are expected to bring further clarity as more data becomes available and new initiatives take shape.

Researchers emphasize the importance of staying informed and engaged. Public participation in the dialogue around these issues can significantly influence the direction of future policies and programs. Education and awareness campaigns are being launched to ensure that all community members have access to reliable information.

Looking ahead, the consensus among experts is cautiously optimistic. While challenges remain, the collective effort to address them demonstrates a resilience and determination that bodes well for the future. Continued collaboration between public and private sectors will be essential in turning these challenges into opportunities for positive change.
''';

  static final List<Article> articles = [
    // POLITICS
    Article(
      id: '1',
      title: 'Global Leaders Summit Addresses Climate Policy Framework',
      content: _loremContent,
      summary: 'World leaders convene to discuss new climate policies and set ambitious targets for carbon reduction by 2030.',
      imageUrl: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800',
      categoryId: 'politics',
      categoryName: 'Politics',
      authorName: 'John Smith',
      authorAvatar: 'https://i.pravatar.cc/150?img=1',
      source: 'Reuters',
      publishedAt: DateTime.now().subtract(const Duration(hours: 2)),
      readTimeMinutes: 5,
      views: 12400,
      isBreaking: true,
      tags: ['Climate', 'Policy', 'Summit'],
      translations: {
        'hi': ArticleTranslation(
          title: 'वैश्विक नेता शिखर सम्मेलन जलवायु नीति रूपरेखा को संबोधित करता है',
          summary: 'विश्व नेता 2030 तक कार्बन में कमी के लिए नई जलवायु नीतियों पर चर्चा करने और महत्वाकांक्षी लक्ष्य निर्धारित करने के लिए एकत्रित हुए।',
          content: '''तेजी से विकसित हो रही दुनिया में, विकास अभूतपूर्व तरीकों से हमारे दैनिक जीवन को आकार देना जारी रखता है। विशेषज्ञ और विश्लेषक स्थिति की बारीकी से निगरानी कर रहे हैं, जो अंतर्दृष्टि प्रदान करते हैं जो हमें इन परिवर्तनों के व्यापक निहितार्थों को समझने में मदद करते हैं।

हाल की रिपोर्टों के अनुसार, प्रभाव कई क्षेत्रों में महत्वपूर्ण रहा है। उद्योग के नेताओं ने आशावाद और सावधानी दोनों व्यक्त की है, इन जटिल गतिशीलता को नेविगेट करने के लिए संतुलित दृष्टिकोण की आवश्यकता पर जोर दिया है।

"हम एक महत्वपूर्ण क्षण पर हैं," डॉ. सारा चेन ने कहा, जो इस क्षेत्र में एक प्रमुख शोधकर्ता हैं। "आज हम जो निर्णय लेते हैं, उनके आने वाली पीढ़ियों के लिए स्थायी परिणाम होंगे। यह महत्वपूर्ण है कि हम इसे तात्कालिकता और विचारशीलता दोनों के साथ देखें।"

डेटा परिवर्तन की ओर एक स्पष्ट प्रवृत्ति का सुझाव देता है। नवीनतम तिमाही के आंकड़े उपभोक्ता व्यवहार, तकनीकी अपनाने और नीति ढांचे में उल्लेखनीय बदलाव दिखाते हैं।''',
          categoryName: 'राजनीति',
        ),
        'ta': ArticleTranslation(
          title: 'உலகளாவிய தலைவர்கள் உச்சி மாநாடு காலநிலை கொள்கை கட்டமைப்பை உரையாற்றுகிறது',
          summary: 'உலக தலைவர்கள் புதிய காலநிலை கொள்கைகளைப் பற்றி விவாதிக்கவும் 2030 க்குள் கார்பன் குறைப்புக்கான லட்சிய இலக்குகளை அமைக்கவும் கூடுகின்றனர்.',
          content: '''வேகமாக வளர்ந்து வரும் உலகில், முன்னேற்றங்கள் முன்னோடியில்லாத வழிகளில் நமது அன்றாட வாழ்க்கையை தொடர்ந்து வடிவமைக்கின்றன. நிபுணர்கள் மற்றும் பகுப்பாய்வாளர்கள் நிலைமையை உன்னிப்பாகக் கண்காணித்து, இந்த மாற்றங்களின் பரந்த தாக்கங்களைப் புரிந்துகொள்ள உதவும் நுண்ணறிவுகளை வழங்குகின்றனர்.

சமீபத்திய அறிக்கைகளின்படி, பல துறைகளில் தாக்கம் குறிப்பிடத்தக்கதாக உள்ளது. தொழில் தலைவர்கள் நம்பிக்கை மற்றும் எச்சரிக்கை இரண்டையும் வெளிப்படுத்தியுள்ளனர், இந்த சிக்கலான இயக்கவியலை வழிநடத்த சமநிலையான அணுகுமுறைகளின் அவசியத்தை வலியுறுத்துகின்றனர்.

"நாம் ஒரு முக்கியமான தருணத்தில் இருக்கிறோம்," என்று டாக்டர் சாரா சென் கூறினார், இந்த துறையில் முன்னணி ஆராய்ச்சியாளர். "இன்று நாம் எடுக்கும் முடிவுகள் தலைமுறைகளுக்கு நீடித்த விளைவுகளை ஏற்படுத்தும். அவசரம் மற்றும் சிந்தனையுடன் இதை அணுகுவது மிக முக்கியம்."

தரவு மாற்றத்தை நோக்கி ஒரு தெளிவான போக்கை பரிந்துரைக்கிறது. சமீபத்திய காலாண்டின் புள்ளிவிவரங்கள் நுகர்வோர் நடத்தை, தொழில்நுட்ப தத்தெடுப்பு மற்றும் கொள்கை கட்டமைப்புகளில் குறிப்பிடத்தக்க மாற்றங்களைக் காட்டுகின்றன.''',
          categoryName: 'அரசியல்',
        ),
        'te': ArticleTranslation(
          title: 'గ్లోబల్ లీడర్స్ సమ్మిట్ వాతావరణ విధాన ఫ్రేమ్‌వర్క్‌ను ప్రస్తావిస్తుంది',
          summary: 'ప్రపంచ నాయకులు కొత్త వాతావరణ విధానాలను చర్చించడానికి మరియు 2030 నాటికి కార్బన్ తగ్గింపు కోసం ప్రతిష్టాత్మక లక్ష్యాలను నిర్ణయించడానికి సమావేశమయ్యారు.',
          content: '''వేగంగా అభివృద్ధి చెందుతున్న ప్రపంచంలో, అభివృద్ధి అపూర్వమైన మార్గాల్లో మన రోజువారీ జీవితాలను రూపొందించడం కొనసాగిస్తుంది. నిపుణులు మరియు విశ్లేషకులు పరిస్థితిని నిశితంగా పర్యవేక్షిస్తున్నారు, ఈ మార్పుల విస్తృత చిక్కులను అర్థం చేసుకోవడంలో సహాయపడే అంతర్దృష్టులను అందిస్తున్నారు.

ఇటీవలి నివేదికల ప్రకారం, అనేక రంగాలలో ప్రభావం గణనీయంగా ఉంది. పరిశ్రమ నాయకులు ఆశావాదం మరియు హెచ్చరికను వ్యక్తం చేశారు, ఈ సంక్లిష్ట డైనమిక్స్‌ను నావిగేట్ చేయడానికి సమతుల్య విధానాల అవసరాన్ని నొక్కి చెప్పారు.

"మేము ఒక కీలకమైన సమయంలో ఉన్నాము," అని డాక్టర్ సారా చెన్ అన్నారు, ఈ రంగంలో ప్రముఖ పరిశోధకుడు. "ఈ రోజు మనం తీసుకునే నిర్ణయాలు తరతరాలకు శాశ్వత పరిణామాలను కలిగి ఉంటాయి. దీనిని అత్యవసరత మరియు ఆలోచనాత్మకతతో చేరుకోవడం చాలా కీలకం."

డేటా రూపాంతరం వైపు స్పష్టమైన ధోరణిని సూచిస్తుంది. తాజా త్రైమాసికం నుండి గణాంకాలు వినియోగదారు ప్రవర్తన, సాంకేతిక స్వీకరణ మరియు విధాన ఫ్రేమ్‌వర్క్‌లలో గమనించదగిన మార్పులను చూపుతున్నాయి.''',
          categoryName: 'రాజకీయాలు',
        ),
      },
    ),
    Article(
      id: '2',
      title: 'Senate Passes Historic Infrastructure Bill With Bipartisan Support',
      content: _loremContent,
      summary: 'The landmark \$1.2 trillion infrastructure bill receives overwhelming bipartisan support in the Senate.',
      imageUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800',
      categoryId: 'politics',
      categoryName: 'Politics',
      authorName: 'Emily Davis',
      authorAvatar: 'https://i.pravatar.cc/150?img=5',
      source: 'AP News',
      publishedAt: DateTime.now().subtract(const Duration(hours: 5)),
      readTimeMinutes: 7,
      views: 8900,
      tags: ['Infrastructure', 'Senate', 'Legislation'],
      translations: {
        'hi': ArticleTranslation(
          title: 'सीनेट ने द्विदलीय समर्थन के साथ ऐतिहासिक बुनियादी ढांचा विधेयक पारित किया',
          summary: 'ऐतिहासिक \$1.2 ट्रिलियन बुनियादी ढांचा विधेयक को सीनेट में भारी द्विदलीय समर्थन मिला।',
          content: 'तेजी से विकसित हो रही दुनिया में, बुनियादी ढांचे के विकास ने एक नया आयाम लिया है। विशेषज्ञों का कहना है कि यह विधेयक देश के विकास में एक महत्वपूर्ण मील का पत्थर साबित होगा। इस विधेयक से सड़कों, पुलों और सार्वजनिक परिवहन में सुधार की उम्मीद है।',
          categoryName: 'राजनीति',
        ),
        'ta': ArticleTranslation(
          title: 'செனட் இரு கட்சி ஆதரவுடன் வரலாற்று உள்கட்டமைப்பு மசோதாவை நிறைவேற்றியது',
          summary: 'முக்கிய \$1.2 டிரில்லியன் உள்கட்டமைப்பு மசோதா செனட்டில் பெரும் இரு கட்சி ஆதரவைப் பெறுகிறது.',
          content: 'வேகமாக வளர்ந்து வரும் உலகில், உள்கட்டமைப்பு மேம்பாடு ஒரு புதிய பரிமாணத்தை எடுத்துள்ளது. இந்த மசோதா நாட்டின் வளர்ச்சியில் ஒரு முக்கியமான மைல்கல்லாக இருக்கும் என்று நிபுணர்கள் கூறுகின்றனர். இந்த மசோதாவிலிருந்து சாலைகள், பாலங்கள் மற்றும் பொது போக்குவரத்தில் முன்னேற்றம் எதிர்பார்க்கப்படுகிறது.',
          categoryName: 'அரசியல்',
        ),
        'te': ArticleTranslation(
          title: 'సెనేట్ ద్వైపాక్షిక మద్దతుతో చారిత్రాత్మక మౌలిక సదుపాయాల బిల్లును ఆమోదించింది',
          summary: 'మైలురాయి \$1.2 ట్రిలియన్ల మౌలిక సదుపాయాల బిల్లు సెనేట్‌లో అత్యధిక ద్వైపాక్షిక మద్దతును పొందింది.',
          content: 'వేగంగా అభివృద్ధి చెందుతున్న ప్రపంచంలో, మౌలిక సదుపాయాల అభివృద్ధి కొత్త కోణాన్ని తీసుకుంది. ఈ బిల్లు దేశ అభివృద్ధిలో ఒక ముఖ్యమైన మైలురాయిగా నిలుస్తుందని నిపుణులు అంటున్నారు. ఈ బిల్లు నుండి రోడ్లు, వంతెనలు మరియు ప్రజా రవాణాలో మెరుగుదల ఆశించబడుతోంది.',
          categoryName: 'రాజకీయాలు',
        ),
      },
    ),
    Article(
      id: '3',
      title: 'Election Commission Announces New Digital Voting Guidelines',
      content: _loremContent,
      summary: 'New guidelines aim to modernize the voting process while maintaining security and transparency.',
      imageUrl: 'https://images.unsplash.com/photo-1494172961521-33799ddd43a5?w=800',
      categoryId: 'politics',
      categoryName: 'Politics',
      authorName: 'Michael Brown',
      authorAvatar: 'https://i.pravatar.cc/150?img=3',
      source: 'BBC News',
      publishedAt: DateTime.now().subtract(const Duration(hours: 8)),
      readTimeMinutes: 4,
      views: 6700,
      tags: ['Election', 'Digital', 'Voting'],
    ),
    Article(
      id: '4',
      title: 'International Trade Agreement Signed Between Major Economies',
      content: _loremContent,
      summary: 'A comprehensive trade agreement promises to boost economic cooperation and reduce tariffs.',
      imageUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800',
      categoryId: 'politics',
      categoryName: 'Politics',
      authorName: 'Sarah Wilson',
      authorAvatar: 'https://i.pravatar.cc/150?img=10',
      source: 'Bloomberg',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      readTimeMinutes: 6,
      views: 5400,
      tags: ['Trade', 'Economy', 'International'],
    ),
    Article(
      id: '5',
      title: 'Defense Secretary Outlines New National Security Strategy',
      content: _loremContent,
      summary: 'The updated strategy focuses on cybersecurity threats and modern defense capabilities.',
      imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800',
      categoryId: 'politics',
      categoryName: 'Politics',
      authorName: 'Robert Taylor',
      authorAvatar: 'https://i.pravatar.cc/150?img=7',
      source: 'CNN',
      publishedAt: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
      readTimeMinutes: 8,
      views: 4200,
      tags: ['Defense', 'Security', 'Cybersecurity'],
    ),

    // SPORTS
    Article(
      id: '6',
      title: 'Champions League Final: Historic Victory Stuns the World',
      content: _loremContent,
      summary: 'An underdog team clinches the Champions League title in a dramatic penalty shootout.',
      imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
      categoryId: 'sports',
      categoryName: 'Sports',
      authorName: 'Jake Anderson',
      authorAvatar: 'https://i.pravatar.cc/150?img=11',
      source: 'ESPN',
      publishedAt: DateTime.now().subtract(const Duration(hours: 1)),
      readTimeMinutes: 4,
      views: 24500,
      isBreaking: true,
      tags: ['Football', 'Champions League', 'Final'],
    ),
    Article(
      id: '7',
      title: 'Olympic Committee Announces New Sports for 2028 Games',
      content: _loremContent,
      summary: 'Five new sports will make their debut at the upcoming Olympic Games in Los Angeles.',
      imageUrl: 'https://images.unsplash.com/photo-1461896836934-bd45ba8c0e78?w=800',
      categoryId: 'sports',
      categoryName: 'Sports',
      authorName: 'Lisa Chen',
      authorAvatar: 'https://i.pravatar.cc/150?img=9',
      source: 'Sports Illustrated',
      publishedAt: DateTime.now().subtract(const Duration(hours: 6)),
      readTimeMinutes: 5,
      views: 15600,
      tags: ['Olympics', 'Sports', '2028'],
    ),
    Article(
      id: '8',
      title: 'Tennis Star Breaks Grand Slam Record in Melbourne',
      content: _loremContent,
      summary: 'A remarkable performance sees the world number one secure their 25th Grand Slam title.',
      imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800',
      categoryId: 'sports',
      categoryName: 'Sports',
      authorName: 'Tom Mitchell',
      authorAvatar: 'https://i.pravatar.cc/150?img=12',
      source: 'Sky Sports',
      publishedAt: DateTime.now().subtract(const Duration(hours: 10)),
      readTimeMinutes: 3,
      views: 11200,
      tags: ['Tennis', 'Grand Slam', 'Record'],
    ),
    Article(
      id: '9',
      title: 'NBA Draft Prospects: Top 10 Players to Watch This Season',
      content: _loremContent,
      summary: 'Scouting experts reveal the most promising young talents heading into the NBA draft.',
      imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800',
      categoryId: 'sports',
      categoryName: 'Sports',
      authorName: 'Chris Johnson',
      authorAvatar: 'https://i.pravatar.cc/150?img=15',
      source: 'Bleacher Report',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      readTimeMinutes: 6,
      views: 9800,
      tags: ['NBA', 'Draft', 'Basketball'],
    ),
    Article(
      id: '10',
      title: 'Formula 1: New Regulations Promise Closer Racing in 2026',
      content: _loremContent,
      summary: 'Revolutionary aerodynamic rules and power unit changes aim to level the playing field.',
      imageUrl: 'https://images.unsplash.com/photo-1541447271487-09612b3f49f7?w=800',
      categoryId: 'sports',
      categoryName: 'Sports',
      authorName: 'Maria Garcia',
      authorAvatar: 'https://i.pravatar.cc/150?img=16',
      source: 'Motorsport.com',
      publishedAt: DateTime.now().subtract(const Duration(days: 2)),
      readTimeMinutes: 7,
      views: 7500,
      tags: ['F1', 'Racing', 'Regulations'],
    ),

    // TECHNOLOGY
    Article(
      id: '11',
      title: 'AI Breakthrough: New Model Achieves Human-Level Reasoning',
      content: _loremContent,
      summary: 'Researchers develop an AI system that demonstrates unprecedented reasoning capabilities across complex tasks.',
      imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
      categoryId: 'tech',
      categoryName: 'Technology',
      authorName: 'Alex Rivera',
      authorAvatar: 'https://i.pravatar.cc/150?img=20',
      source: 'TechCrunch',
      publishedAt: DateTime.now().subtract(const Duration(hours: 3)),
      readTimeMinutes: 6,
      views: 31200,
      isBreaking: true,
      tags: ['AI', 'Machine Learning', 'Research'],
    ),
    Article(
      id: '12',
      title: 'Apple Unveils Revolutionary Mixed Reality Headset',
      content: _loremContent,
      summary: 'The tech giant reveals its next-generation spatial computing device with stunning capabilities.',
      imageUrl: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?w=800',
      categoryId: 'tech',
      categoryName: 'Technology',
      authorName: 'Jennifer Park',
      authorAvatar: 'https://i.pravatar.cc/150?img=21',
      source: 'The Verge',
      publishedAt: DateTime.now().subtract(const Duration(hours: 7)),
      readTimeMinutes: 8,
      views: 28500,
      tags: ['Apple', 'VR', 'AR', 'Mixed Reality'],
    ),
    Article(
      id: '13',
      title: 'Quantum Computing Milestone: 1000 Qubit Processor Achieved',
      content: _loremContent,
      summary: 'A major quantum computing company achieves a significant milestone in processor development.',
      imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800',
      categoryId: 'tech',
      categoryName: 'Technology',
      authorName: 'David Kim',
      authorAvatar: 'https://i.pravatar.cc/150?img=22',
      source: 'Wired',
      publishedAt: DateTime.now().subtract(const Duration(hours: 12)),
      readTimeMinutes: 5,
      views: 19800,
      tags: ['Quantum', 'Computing', 'Processor'],
    ),
    Article(
      id: '14',
      title: 'SpaceX Successfully Tests Starship for Mars Mission',
      content: _loremContent,
      summary: 'The latest Starship test brings humanity one step closer to becoming a multi-planetary species.',
      imageUrl: 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?w=800',
      categoryId: 'tech',
      categoryName: 'Technology',
      authorName: 'Rachel Adams',
      authorAvatar: 'https://i.pravatar.cc/150?img=23',
      source: 'Space.com',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      readTimeMinutes: 4,
      views: 22100,
      tags: ['SpaceX', 'Mars', 'Space'],
    ),
    Article(
      id: '15',
      title: 'Electric Vehicle Sales Surge 150% in Record-Breaking Quarter',
      content: _loremContent,
      summary: 'Global EV adoption accelerates as new models and charging infrastructure expand rapidly.',
      imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800',
      categoryId: 'tech',
      categoryName: 'Technology',
      authorName: 'Mark Stevens',
      authorAvatar: 'https://i.pravatar.cc/150?img=25',
      source: 'Forbes',
      publishedAt: DateTime.now().subtract(const Duration(days: 2)),
      readTimeMinutes: 5,
      views: 14200,
      tags: ['EV', 'Electric', 'Auto'],
    ),

    // ENTERTAINMENT
    Article(
      id: '16',
      title: 'Oscar Nominations 2026: Surprises and Snubs Revealed',
      content: _loremContent,
      summary: 'The Academy announces this year\'s nominations with several unexpected inclusions and notable omissions.',
      imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
      categoryId: 'entertainment',
      categoryName: 'Entertainment',
      authorName: 'Sophie Martinez',
      authorAvatar: 'https://i.pravatar.cc/150?img=30',
      source: 'Variety',
      publishedAt: DateTime.now().subtract(const Duration(hours: 4)),
      readTimeMinutes: 5,
      views: 18700,
      isBreaking: true,
      tags: ['Oscars', 'Movies', 'Awards'],
    ),
    Article(
      id: '17',
      title: 'Streaming Wars: Netflix Launches Revolutionary Interactive Series',
      content: _loremContent,
      summary: 'Netflix debuts a groundbreaking interactive series that lets viewers shape the storyline in real-time.',
      imageUrl: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=800',
      categoryId: 'entertainment',
      categoryName: 'Entertainment',
      authorName: 'James Lee',
      authorAvatar: 'https://i.pravatar.cc/150?img=31',
      source: 'Hollywood Reporter',
      publishedAt: DateTime.now().subtract(const Duration(hours: 9)),
      readTimeMinutes: 4,
      views: 15300,
      tags: ['Netflix', 'Streaming', 'Interactive'],
    ),
    Article(
      id: '18',
      title: 'Global Music Festival Announces Star-Studded 2026 Lineup',
      content: _loremContent,
      summary: 'The world\'s biggest music festival reveals a record-breaking lineup featuring top artists.',
      imageUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
      categoryId: 'entertainment',
      categoryName: 'Entertainment',
      authorName: 'Nicole White',
      authorAvatar: 'https://i.pravatar.cc/150?img=32',
      source: 'Billboard',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      readTimeMinutes: 3,
      views: 12100,
      tags: ['Music', 'Festival', 'Concert'],
    ),
    Article(
      id: '19',
      title: 'Video Game Industry Sets New Revenue Record in 2025',
      content: _loremContent,
      summary: 'The gaming industry surpasses \$200 billion in annual revenue for the first time.',
      imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800',
      categoryId: 'entertainment',
      categoryName: 'Entertainment',
      authorName: 'Ryan Cooper',
      authorAvatar: 'https://i.pravatar.cc/150?img=33',
      source: 'IGN',
      publishedAt: DateTime.now().subtract(const Duration(days: 2)),
      readTimeMinutes: 6,
      views: 9400,
      tags: ['Gaming', 'Revenue', 'Industry'],
    ),

    // BUSINESS
    Article(
      id: '20',
      title: 'Wall Street Reaches All-Time High Amid Tech Rally',
      content: _loremContent,
      summary: 'Major stock indexes hit record levels driven by exceptional tech sector performance.',
      imageUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800',
      categoryId: 'business',
      categoryName: 'Business',
      authorName: 'Patricia Wong',
      authorAvatar: 'https://i.pravatar.cc/150?img=40',
      source: 'Wall Street Journal',
      publishedAt: DateTime.now().subtract(const Duration(hours: 2)),
      readTimeMinutes: 5,
      views: 21300,
      tags: ['Stocks', 'Wall Street', 'Markets'],
    ),
    Article(
      id: '21',
      title: 'Startup Ecosystem Thrives: Record VC Funding in Q1 2026',
      content: _loremContent,
      summary: 'Venture capital investment reaches new heights with AI and biotech startups leading the charge.',
      imageUrl: 'https://images.unsplash.com/photo-1553729459-afe8f2e2882d?w=800',
      categoryId: 'business',
      categoryName: 'Business',
      authorName: 'Daniel Foster',
      authorAvatar: 'https://i.pravatar.cc/150?img=41',
      source: 'Financial Times',
      publishedAt: DateTime.now().subtract(const Duration(hours: 11)),
      readTimeMinutes: 7,
      views: 13600,
      tags: ['Startup', 'VC', 'Funding'],
    ),
    Article(
      id: '22',
      title: 'Remote Work Revolution: 75% of Companies Adopt Hybrid Models',
      content: _loremContent,
      summary: 'A comprehensive study reveals the permanent shift in workplace dynamics post-pandemic.',
      imageUrl: 'https://images.unsplash.com/photo-1587560699334-cc4ff634909a?w=800',
      categoryId: 'business',
      categoryName: 'Business',
      authorName: 'Emma Thompson',
      authorAvatar: 'https://i.pravatar.cc/150?img=42',
      source: 'Business Insider',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      readTimeMinutes: 4,
      views: 10800,
      tags: ['Remote Work', 'Hybrid', 'Workplace'],
    ),
    Article(
      id: '23',
      title: 'Global Supply Chain Overhaul: AI Transforms Logistics Industry',
      content: _loremContent,
      summary: 'Artificial intelligence is revolutionizing supply chain management with predictive analytics.',
      imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800',
      categoryId: 'business',
      categoryName: 'Business',
      authorName: 'Kevin O\'Brien',
      authorAvatar: 'https://i.pravatar.cc/150?img=43',
      source: 'CNBC',
      publishedAt: DateTime.now().subtract(const Duration(days: 2)),
      readTimeMinutes: 6,
      views: 7900,
      tags: ['Supply Chain', 'AI', 'Logistics'],
    ),

    // HEALTH
    Article(
      id: '24',
      title: 'Breakthrough Cancer Treatment Shows 90% Success Rate in Trials',
      content: _loremContent,
      summary: 'A revolutionary immunotherapy treatment demonstrates remarkable results in clinical trials.',
      imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800',
      categoryId: 'health',
      categoryName: 'Health',
      authorName: 'Dr. Amanda Brooks',
      authorAvatar: 'https://i.pravatar.cc/150?img=50',
      source: 'Medical News Today',
      publishedAt: DateTime.now().subtract(const Duration(hours: 3)),
      readTimeMinutes: 6,
      views: 35600,
      isBreaking: true,
      tags: ['Cancer', 'Treatment', 'Immunotherapy'],
    ),
    Article(
      id: '25',
      title: 'Mental Health Awareness: New Study Reveals Impact of Social Media',
      content: _loremContent,
      summary: 'Research highlights the complex relationship between social media use and mental health outcomes.',
      imageUrl: 'https://images.unsplash.com/photo-1493836512294-502baa1986e2?w=800',
      categoryId: 'health',
      categoryName: 'Health',
      authorName: 'Dr. James Miller',
      authorAvatar: 'https://i.pravatar.cc/150?img=51',
      source: 'Psychology Today',
      publishedAt: DateTime.now().subtract(const Duration(hours: 8)),
      readTimeMinutes: 5,
      views: 14200,
      tags: ['Mental Health', 'Social Media', 'Study'],
    ),
    Article(
      id: '26',
      title: 'WHO Approves New Universal Flu Vaccine for Global Distribution',
      content: _loremContent,
      summary: 'A next-generation flu vaccine promises broader protection against multiple influenza strains.',
      imageUrl: 'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=800',
      categoryId: 'health',
      categoryName: 'Health',
      authorName: 'Laura Hernandez',
      authorAvatar: 'https://i.pravatar.cc/150?img=52',
      source: 'WHO News',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      readTimeMinutes: 4,
      views: 11500,
      tags: ['Vaccine', 'WHO', 'Influenza'],
    ),
    Article(
      id: '27',
      title: 'Nutrition Science Update: Mediterranean Diet Linked to Longevity',
      content: _loremContent,
      summary: 'A decade-long study confirms the significant health benefits of the Mediterranean diet.',
      imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800',
      categoryId: 'health',
      categoryName: 'Health',
      authorName: 'Dr. Robert Chen',
      authorAvatar: 'https://i.pravatar.cc/150?img=53',
      source: 'Health Magazine',
      publishedAt: DateTime.now().subtract(const Duration(days: 2)),
      readTimeMinutes: 5,
      views: 8700,
      tags: ['Nutrition', 'Diet', 'Longevity'],
    ),

    // SCIENCE
    Article(
      id: '28',
      title: 'NASA Discovers Water on Distant Exoplanet in Habitable Zone',
      content: _loremContent,
      summary: 'The James Webb Space Telescope detects water vapor in the atmosphere of a potentially habitable world.',
      imageUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800',
      categoryId: 'science',
      categoryName: 'Science',
      authorName: 'Dr. Neil Patterson',
      authorAvatar: 'https://i.pravatar.cc/150?img=55',
      source: 'NASA',
      publishedAt: DateTime.now().subtract(const Duration(hours: 5)),
      readTimeMinutes: 7,
      views: 42000,
      isBreaking: true,
      tags: ['NASA', 'Exoplanet', 'Space'],
    ),
    Article(
      id: '29',
      title: 'Ancient DNA Reveals New Human Species in Southeast Asia',
      content: _loremContent,
      summary: 'Archaeological findings challenge our understanding of human evolution with discovery of new hominin species.',
      imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800',
      categoryId: 'science',
      categoryName: 'Science',
      authorName: 'Prof. Diana Shaw',
      authorAvatar: 'https://i.pravatar.cc/150?img=56',
      source: 'Nature',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      readTimeMinutes: 8,
      views: 19500,
      tags: ['Archaeology', 'DNA', 'Evolution'],
    ),
    Article(
      id: '30',
      title: 'Deep Sea Exploration Reveals New Ecosystem Near Ocean Floor',
      content: _loremContent,
      summary: 'Marine scientists discover a thriving ecosystem thousands of meters below the ocean surface.',
      imageUrl: 'https://images.unsplash.com/photo-1551244072-5d12893278ab?w=800',
      categoryId: 'science',
      categoryName: 'Science',
      authorName: 'Dr. Ocean Wright',
      authorAvatar: 'https://i.pravatar.cc/150?img=57',
      source: 'Scientific American',
      publishedAt: DateTime.now().subtract(const Duration(days: 2)),
      readTimeMinutes: 5,
      views: 13800,
      tags: ['Ocean', 'Discovery', 'Marine'],
    ),
  ];

  static final List<Comment> comments = [
    Comment(id: 'c1', articleId: '1', userName: 'Alice Johnson', userAvatar: 'https://i.pravatar.cc/150?img=60', content: 'This is a great step forward for climate action. We need more leaders to commit to these targets.', createdAt: DateTime.now().subtract(const Duration(hours: 1)), likes: 24),
    Comment(id: 'c2', articleId: '1', userName: 'Bob Williams', userAvatar: 'https://i.pravatar.cc/150?img=61', content: 'I hope this translates into real action and not just empty promises.', createdAt: DateTime.now().subtract(const Duration(hours: 1, minutes: 30)), likes: 18),
    Comment(id: 'c3', articleId: '1', userName: 'Carol Davis', userAvatar: 'https://i.pravatar.cc/150?img=62', content: 'Finally some good news! The framework seems comprehensive and achievable.', createdAt: DateTime.now().subtract(const Duration(hours: 2)), likes: 12),
    Comment(id: 'c4', articleId: '6', userName: 'Dan Miller', userAvatar: 'https://i.pravatar.cc/150?img=63', content: 'What a match! Best Champions League final I\'ve ever watched!', createdAt: DateTime.now().subtract(const Duration(minutes: 30)), likes: 56),
    Comment(id: 'c5', articleId: '6', userName: 'Eve Brown', userAvatar: 'https://i.pravatar.cc/150?img=64', content: 'The underdog story is absolutely incredible. Pure football magic!', createdAt: DateTime.now().subtract(const Duration(minutes: 45)), likes: 34),
    Comment(id: 'c6', articleId: '11', userName: 'Frank Wilson', userAvatar: 'https://i.pravatar.cc/150?img=65', content: 'This is both exciting and slightly terrifying. The pace of AI development is incredible.', createdAt: DateTime.now().subtract(const Duration(hours: 2)), likes: 42),
    Comment(id: 'c7', articleId: '11', userName: 'Grace Lee', userAvatar: 'https://i.pravatar.cc/150?img=66', content: 'As a researcher in the field, I can confirm this is a significant breakthrough.', createdAt: DateTime.now().subtract(const Duration(hours: 2, minutes: 15)), likes: 38),
    Comment(id: 'c8', articleId: '24', userName: 'Henry Taylor', userAvatar: 'https://i.pravatar.cc/150?img=67', content: 'This gives so much hope to cancer patients worldwide. Science is amazing!', createdAt: DateTime.now().subtract(const Duration(hours: 1)), likes: 67),
    Comment(id: 'c9', articleId: '28', userName: 'Iris Zhang', userAvatar: 'https://i.pravatar.cc/150?img=68', content: 'Finding water on an exoplanet is a huge milestone. Can\'t wait for more discoveries!', createdAt: DateTime.now().subtract(const Duration(hours: 3)), likes: 51),
    Comment(id: 'c10', articleId: '20', userName: 'Jack Robinson', userAvatar: 'https://i.pravatar.cc/150?img=69', content: 'The market rally seems sustainable with strong fundamentals backing it.', createdAt: DateTime.now().subtract(const Duration(hours: 1)), likes: 15),
  ];

  static final List<AppUser> users = [
    AppUser(id: 'u1', name: 'John Doe', email: 'john@example.com', avatarUrl: 'https://i.pravatar.cc/150?img=1', joinedAt: DateTime(2024, 1, 15), articlesRead: 245, bookmarksCount: 32),
    AppUser(id: 'u2', name: 'Jane Smith', email: 'jane@example.com', avatarUrl: 'https://i.pravatar.cc/150?img=5', joinedAt: DateTime(2024, 3, 22), articlesRead: 189, bookmarksCount: 28),
    AppUser(id: 'u3', name: 'Mike Johnson', email: 'mike@example.com', avatarUrl: 'https://i.pravatar.cc/150?img=8', joinedAt: DateTime(2024, 5, 10), articlesRead: 156, bookmarksCount: 15),
    AppUser(id: 'u4', name: 'Sarah Williams', email: 'sarah@example.com', avatarUrl: 'https://i.pravatar.cc/150?img=10', joinedAt: DateTime(2024, 7, 4), articlesRead: 312, bookmarksCount: 45),
    AppUser(id: 'u5', name: 'Chris Brown', email: 'chris@example.com', avatarUrl: 'https://i.pravatar.cc/150?img=12', joinedAt: DateTime(2024, 8, 19), isBlocked: true, articlesRead: 78, bookmarksCount: 5),
    AppUser(id: 'u6', name: 'Emily Davis', email: 'emily@example.com', avatarUrl: 'https://i.pravatar.cc/150?img=15', joinedAt: DateTime(2024, 9, 1), articlesRead: 98, bookmarksCount: 12),
    AppUser(id: 'u7', name: 'David Wilson', email: 'david@example.com', avatarUrl: 'https://i.pravatar.cc/150?img=18', joinedAt: DateTime(2024, 10, 12), articlesRead: 67, bookmarksCount: 8),
    AppUser(id: 'u8', name: 'Lisa Anderson', email: 'lisa@example.com', avatarUrl: 'https://i.pravatar.cc/150?img=20', joinedAt: DateTime(2025, 1, 5), articlesRead: 134, bookmarksCount: 22),
    AppUser(id: 'admin', name: 'Admin User', email: 'admin@newsportal.com', avatarUrl: 'https://i.pravatar.cc/150?img=70', joinedAt: DateTime(2023, 6, 1), isAdmin: true, articlesRead: 500, bookmarksCount: 50),
  ];

  static final List<AppNotification> notifications = [
    AppNotification(id: 'n1', title: 'Breaking News', body: 'Global Leaders Summit Addresses Climate Policy Framework', type: 'breaking', createdAt: DateTime.now().subtract(const Duration(hours: 2)), articleId: '1'),
    AppNotification(id: 'n2', title: 'Sports Alert', body: 'Champions League Final: Historic Victory Stuns the World', type: 'breaking', createdAt: DateTime.now().subtract(const Duration(hours: 1)), articleId: '6'),
    AppNotification(id: 'n3', title: 'Tech Update', body: 'AI Breakthrough: New Model Achieves Human-Level Reasoning', type: 'article', createdAt: DateTime.now().subtract(const Duration(hours: 3)), articleId: '11'),
    AppNotification(id: 'n4', title: 'Health News', body: 'Breakthrough Cancer Treatment Shows 90% Success Rate', type: 'breaking', createdAt: DateTime.now().subtract(const Duration(hours: 3)), articleId: '24'),
    AppNotification(id: 'n5', title: 'Science Discovery', body: 'NASA Discovers Water on Distant Exoplanet', type: 'article', createdAt: DateTime.now().subtract(const Duration(hours: 5)), articleId: '28'),
    AppNotification(id: 'n6', title: 'Welcome!', body: 'Welcome to News Portal! Customize your news feed preferences.', type: 'system', createdAt: DateTime.now().subtract(const Duration(days: 1))),
    AppNotification(id: 'n7', title: 'Weekly Digest', body: 'Your weekly news digest is ready. Tap to read the top stories.', type: 'system', createdAt: DateTime.now().subtract(const Duration(days: 2)), isRead: true),
    AppNotification(id: 'n8', title: 'New Category', body: 'Science category is now available! Explore the latest discoveries.', type: 'system', createdAt: DateTime.now().subtract(const Duration(days: 3)), isRead: true),
  ];

  static final List<String> trendingTopics = [
    'Climate Change',
    'AI Revolution',
    'Champions League',
    'Space Exploration',
    'Cancer Research',
    'Electric Vehicles',
    'Stock Market',
    'Oscar Nominations',
  ];
}
