import 'package:flutter/material.dart';
import '../models/article.dart';
import '../models/category.dart';
import '../models/user.dart';
import '../models/comment.dart';
import '../models/notification.dart';
import 'article_translations.dart';

class MockData {
  static final List<Category> categories = [
    Category(id: 'all', name: 'All', icon: Icons.public, color: '#1E88E5', articleCount: 30),
    Category(id: 'politics', name: 'Politics', icon: Icons.account_balance, color: '#E53935', articleCount: 5),
    Category(id: 'sports', name: 'Sports', icon: Icons.sports_soccer, color: '#43A047', articleCount: 5),
    Category(id: 'tech', name: 'Technology', icon: Icons.computer, color: '#8E24AA', articleCount: 5),
    Category(id: 'entertainment', name: 'Entertainment', icon: Icons.movie, color: '#FB8C00', articleCount: 4),
    Category(id: 'business', name: 'Business', icon: Icons.business_center, color: '#00897B', articleCount: 4),
    Category(id: 'health', name: 'Health', icon: Icons.health_and_safety, color: '#D81B60', articleCount: 4),
    Category(id: 'science', name: 'Science', icon: Icons.science, color: '#3949AB', articleCount: 3),
  ];

  static const String _loremContent = '''
In a rapidly evolving world, developments continue to shape our daily lives in unprecedented ways. Experts and analysts have been closely monitoring the situation, providing insights that help us understand the broader implications of these changes.

According to recent reports, the impact has been significant across multiple sectors. Industry leaders have expressed both optimism and caution, emphasizing the need for balanced approaches to navigate these complex dynamics.

"We are at a pivotal moment," said Dr. Sarah Chen, a leading researcher in the field. "The decisions we make today will have lasting consequences for generations to come. It's crucial that we approach this with both urgency and thoughtfulness."

The data suggests a clear trend toward transformation. Statistics from the latest quarter show remarkable shifts in consumer behavior, technological adoption, and policy frameworks. These changes are not isolated to any single region but represent a global phenomenon that requires coordinated responses.

Community stakeholders have begun organizing forums and workshops to address the most pressing concerns. Local leaders are working alongside national agencies to develop comprehensive strategies that balance economic growth with social responsibility.

As the situation continues to develop, observers note that adaptability and innovation will be key factors in determining outcomes. The coming months are expected to bring further clarity as more data becomes available and new initiatives take shape.

Researchers emphasize the importance of staying informed and engaged. Public participation in the dialogue around these issues can significantly influence the direction of future policies and programs. Education and awareness campaigns are being launched to ensure that all community members have access to reliable information.

Looking ahead, the consensus among experts is cautiously optimistic. While challenges remain, the collective effort to address them demonstrates a resilience and determination that bodes well for the future. Continued collaboration between public and private sectors will be essential in turning these challenges into opportunities for positive change.
''';

  static final List<Article> articles = [
    // POLITICS
    Article(
      id: '1',
      title: 'Global Leaders Summit Addresses Climate Policy Framework',
      content: _loremContent,
      summary: 'World leaders convene to discuss new climate policies and set ambitious targets for carbon reduction by 2030.',
      imageUrl: 'assets/images/articles/article_1.jpg',
      categoryId: 'politics',
      categoryName: 'Politics',
      authorName: 'John Smith',
      authorAvatar: 'assets/images/avatars/avatar_1.jpg',
      source: 'Reuters',
      publishedAt: DateTime.now().subtract(const Duration(hours: 2)),
      readTimeMinutes: 5,
      views: 12400,
      isBreaking: true,
      tags: ['Climate', 'Policy', 'Summit'],
      translations: {
        'hi': ArticleTranslation(
          title: 'वैश्विक नेता शिखर सम्मेलन जलवायु नीति रूपरेखा को संबोधित करता है',
          summary: 'विश्व नेता 2030 तक कार्बन में कमी के लिए नई जलवायु नीतियों पर चर्चा करने और महत्वाकांक्षी लक्ष्य निर्धारित करने के लिए एकत्रित हुए।',
          content: '''तेजी से विकसित हो रही दुनिया में, विकास अभूतपूर्व तरीकों से हमारे दैनिक जीवन को आकार देना जारी रखता है। विशेषज्ञ और विश्लेषक स्थिति की बारीकी से निगरानी कर रहे हैं, जो अंतर्दृष्टि प्रदान करते हैं जो हमें इन परिवर्तनों के व्यापक निहितार्थों को समझने में मदद करते हैं।

हाल की रिपोर्टों के अनुसार, प्रभाव कई क्षेत्रों में महत्वपूर्ण रहा है। उद्योग के नेताओं ने आशावाद और सावधानी दोनों व्यक्त की है, इन जटिल गतिशीलता को नेविगेट करने के लिए संतुलित दृष्टिकोण की आवश्यकता पर जोर दिया है।

"हम एक महत्वपूर्ण क्षण पर हैं," डॉ. सारा चेन ने कहा, जो इस क्षेत्र में एक प्रमुख शोधकर्ता हैं। "आज हम जो निर्णय लेते हैं, उनके आने वाली पीढ़ियों के लिए स्थायी परिणाम होंगे। यह महत्वपूर्ण है कि हम इसे तात्कालिकता और विचारशीलता दोनों के साथ देखें।"

डेटा परिवर्तन की ओर एक स्पष्ट प्रवृत्ति का सुझाव देता है। नवीनतम तिमाही के आंकड़े उपभोक्ता व्यवहार, तकनीकी अपनाने और नीति ढांचे में उल्लेखनीय बदलाव दिखाते हैं।''',
          categoryName: 'राजनीति',
        ),
        'ta': ArticleTranslation(
          title: 'உலகளாவிய தலைவர்கள் உச்சி மாநாடு காலநிலை கொள்கை கட்டமைப்பை உரையாற்றுகிறது',
          summary: 'உலக தலைவர்கள் புதிய காலநிலை கொள்கைகளைப் பற்றி விவாதிக்கவும் 2030 க்குள் கார்பன் குறைப்புக்கான லட்சிய இலக்குகளை அமைக்கவும் கூடுகின்றனர்.',
          content: '''வேகமாக வளர்ந்து வரும் உலகில், முன்னேற்றங்கள் முன்னோடியில்லாத வழிகளில் நமது அன்றாட வாழ்க்கையை தொடர்ந்து வடிவமைக்கின்றன. நிபுணர்கள் மற்றும் பகுப்பாய்வாளர்கள் நிலைமையை உன்னிப்பாகக் கண்காணித்து, இந்த மாற்றங்களின் பரந்த தாக்கங்களைப் புரிந்துகொள்ள உதவும் நுண்ணறிவுகளை வழங்குகின்றனர்.

சமீபத்திய அறிக்கைகளின்படி, பல துறைகளில் தாக்கம் குறிப்பிடத்தக்கதாக உள்ளது. தொழில் தலைவர்கள் நம்பிக்கை மற்றும் எச்சரிக்கை இரண்டையும் வெளிப்படுத்தியுள்ளனர், இந்த சிக்கலான இயக்கவியலை வழிநடத்த சமநிலையான அணுகுமுறைகளின் அவசியத்தை வலியுறுத்துகின்றனர்.

"நாம் ஒரு முக்கியமான தருணத்தில் இருக்கிறோம்," என்று டாக்டர் சாரா சென் கூறினார், இந்த துறையில் முன்னணி ஆராய்ச்சியாளர். "இன்று நாம் எடுக்கும் முடிவுகள் தலைமுறைகளுக்கு நீடித்த விளைவுகளை ஏற்படுத்தும். அவசரம் மற்றும் சிந்தனையுடன் இதை அணுகுவது மிக முக்கியம்."

தரவு மாற்றத்தை நோக்கி ஒரு தெளிவான போக்கை பரிந்துரைக்கிறது. சமீபத்திய காலாண்டின் புள்ளிவிவரங்கள் நுகர்வோர் நடத்தை, தொழில்நுட்ப தத்தெடுப்பு மற்றும் கொள்கை கட்டமைப்புகளில் குறிப்பிடத்தக்க மாற்றங்களைக் காட்டுகின்றன.''',
          categoryName: 'அரசியல்',
        ),
        'te': ArticleTranslation(
          title: 'గ్లోబల్ లీడర్స్ సమ్మిట్ వాతావరణ విధాన ఫ్రేమ్‌వర్క్‌ను ప్రస్తావిస్తుంది',
          summary: 'ప్రపంచ నాయకులు కొత్త వాతావరణ విధానాలను చర్చించడానికి మరియు 2030 నాటికి కార్బన్ తగ్గింపు కోసం ప్రతిష్టాత్మక లక్ష్యాలను నిర్ణయించడానికి సమావేశమయ్యారు.',
          content: '''వేగంగా అభివృద్ధి చెందుతున్న ప్రపంచంలో, అభివృద్ధి అపూర్వమైన మార్గాల్లో మన రోజువారీ జీవితాలను రూపొందించడం కొనసాగిస్తుంది. నిపుణులు మరియు విశ్లేషకులు పరిస్థితిని నిశితంగా పర్యవేక్షిస్తున్నారు, ఈ మార్పుల విస్తృత చిక్కులను అర్థం చేసుకోవడంలో సహాయపడే అంతర్దృష్టులను అందిస్తున్నారు.

ఇటీవలి నివేదికల ప్రకారం, అనేక రంగాలలో ప్రభావం గణనీయంగా ఉంది. పరిశ్రమ నాయకులు ఆశావాదం మరియు హెచ్చరికను వ్యక్తం చేశారు, ఈ సంక్లిష్ట డైనమిక్స్‌ను నావిగేట్ చేయడానికి సమతుల్య విధానాల అవసరాన్ని నొక్కి చెప్పారు.

"మేము ఒక కీలకమైన సమయంలో ఉన్నాము," అని డాక్టర్ సారా చెన్ అన్నారు, ఈ రంగంలో ప్రముఖ పరిశోధకుడు. "ఈ రోజు మనం తీసుకునే నిర్ణయాలు తరతరాలకు శాశ్వత పరిణామాలను కలిగి ఉంటాయి. దీనిని అత్యవసరత మరియు ఆలోచనాత్మకతతో చేరుకోవడం చాలా కీలకం."

డేటా రూపాంతరం వైపు స్పష్టమైన ధోరణిని సూచిస్తుంది. తాజా త్రైమాసికం నుండి గణాంకాలు వినియోగదారు ప్రవర్తన, సాంకేతిక స్వీకరణ మరియు విధాన ఫ్రేమ్‌వర్క్‌లలో గమనించదగిన మార్పులను చూపుతున్నాయి.''',
          categoryName: 'రాజకీయాలు',
        ),
      },
    ),
    Article(
      id: '2',
      title: 'Senate Passes Historic Infrastructure Bill With Bipartisan Support',
      content: _loremContent,
      summary: 'The landmark \$1.2 trillion infrastructure bill receives overwhelming bipartisan support in the Senate.',
      imageUrl: 'assets/images/articles/article_2.jpg',
      categoryId: 'politics',
      categoryName: 'Politics',
      authorName: 'Emily Davis',
      authorAvatar: 'assets/images/avatars/avatar_5.jpg',
      source: 'AP News',
      publishedAt: DateTime.now().subtract(const Duration(hours: 5)),
      readTimeMinutes: 7,
      views: 8900,
      tags: ['Infrastructure', 'Senate', 'Legislation'],
      translations: {
        'hi': ArticleTranslation(
          title: 'सीनेट ने द्विदलीय समर्थन के साथ ऐतिहासिक बुनियादी ढांचा विधेयक पारित किया',
          summary: 'ऐतिहासिक \$1.2 ट्रिलियन बुनियादी ढांचा विधेयक को सीनेट में भारी द्विदलीय समर्थन मिला।',
          content: 'तेजी से विकसित हो रही दुनिया में, बुनियादी ढांचे के विकास ने एक नया आयाम लिया है। विशेषज्ञों का कहना है कि यह विधेयक देश के विकास में एक महत्वपूर्ण मील का पत्थर साबित होगा। इस विधेयक से सड़कों, पुलों और सार्वजनिक परिवहन में सुधार की उम्मीद है।',
          categoryName: 'राजनीति',
        ),
        'ta': ArticleTranslation(
          title: 'செனட் இரு கட்சி ஆதரவுடன் வரலாற்று உள்கட்டமைப்பு மசோதாவை நிறைவேற்றியது',
          summary: 'முக்கிய \$1.2 டிரில்லியன் உள்கட்டமைப்பு மசோதா செனட்டில் பெரும் இரு கட்சி ஆதரவைப் பெறுகிறது.',
          content: 'வேகமாக வளர்ந்து வரும் உலகில், உள்கட்டமைப்பு மேம்பாடு ஒரு புதிய பரிமாணத்தை எடுத்துள்ளது. இந்த மசோதா நாட்டின் வளர்ச்சியில் ஒரு முக்கியமான மைல்கல்லாக இருக்கும் என்று நிபுணர்கள் கூறுகின்றனர். இந்த மசோதாவிலிருந்து சாலைகள், பாலங்கள் மற்றும் பொது போக்குவரத்தில் முன்னேற்றம் எதிர்பார்க்கப்படுகிறது.',
          categoryName: 'அரசியல்',
        ),
        'te': ArticleTranslation(
          title: 'సెనేట్ ద్వైపాక్షిక మద్దతుతో చారిత్రాత్మక మౌలిక సదుపాయాల బిల్లును ఆమోదించింది',
          summary: 'మైలురాయి \$1.2 ట్రిలియన్ల మౌలిక సదుపాయాల బిల్లు సెనేట్‌లో అత్యధిక ద్వైపాక్షిక మద్దతును పొందింది.',
          content: 'వేగంగా అభివృద్ధి చెందుతున్న ప్రపంచంలో, మౌలిక సదుపాయాల అభివృద్ధి కొత్త కోణాన్ని తీసుకుంది. ఈ బిల్లు దేశ అభివృద్ధిలో ఒక ముఖ్యమైన మైలురాయిగా నిలుస్తుందని నిపుణులు అంటున్నారు. ఈ బిల్లు నుండి రోడ్లు, వంతెనలు మరియు ప్రజా రవాణాలో మెరుగుదల ఆశించబడుతోంది.',
          categoryName: 'రాజకీయాలు',
        ),
      },
    ),
    Article(
      id: '3',
      title: 'Election Commission Announces New Digital Voting Guidelines',
      content: _loremContent,
      summary: 'New guidelines aim to modernize the voting process while maintaining security and transparency.',
      imageUrl: 'assets/images/articles/article_3.jpg',
      categoryId: 'politics',
      categoryName: 'Politics',
      authorName: 'Michael Brown',
      authorAvatar: 'assets/images/avatars/avatar_3.jpg',
      source: 'BBC News',
      publishedAt: DateTime.now().subtract(const Duration(hours: 8)),
      readTimeMinutes: 4,
      views: 6700,
      tags: ['Election', 'Digital', 'Voting'],
      translations: ArticleTranslations.getTranslations(
        'चुनाव आयोग ने नई डिजिटल मतदान दिशानिर्देश की घोषणा की',
        'தேர்தல் ஆணையம் புதிய டிஜிட்டல் வாக்களிப்பு வழிகாட்டுதல்களை அறிவிக்கிறது',
        'ఎన్నికల కమిషన్ కొత్త డిజిటల్ ఓటింగ్ మార్గదర్శకాలను ప్రకటించింది',
        'नई दिशानिर्देश सुरक्षा और पारदर्शिता बनाए रखते हुए मतदान प्रक्रिया को आधुनिक बनाने का लक्ष्य रखती हैं।',
        'புதிய வழிகாட்டுதல்கள் பாதுகாப்பு மற்றும் வெளிப்படைத்தன்மையை பராமரிக்கும் போது வாக்களிப்பு செயல்முறையை நவீனமயமாக்குவதை நோக்கமாகக் கொண்டுள்ளன.',
        'కొత్త మార్గదర్శకాలు భద్రత మరియు పారదర్శకతను కొనసాగిస్తూ ఓటింగ్ ప్రక్రియను ఆధునీకరించడం లక్ష్యంగా పెట్టుకున్నాయి.',
        'राजनीति', 'அரசியல்', 'రాజకీయాలు',
      ),
    ),
    Article(
      id: '4',
      title: 'International Trade Agreement Signed Between Major Economies',
      content: _loremContent,
      summary: 'A comprehensive trade agreement promises to boost economic cooperation and reduce tariffs.',
      imageUrl: 'assets/images/articles/article_4.jpg',
      categoryId: 'politics',
      categoryName: 'Politics',
      authorName: 'Sarah Wilson',
      authorAvatar: 'assets/images/avatars/avatar_10.jpg',
      source: 'Bloomberg',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      readTimeMinutes: 6,
      views: 5400,
      tags: ['Trade', 'Economy', 'International'],
      translations: ArticleTranslations.getTranslations(
        'प्रमुख अर्थव्यवस्थाओं के बीच अंतर्राष्ट्रीय व्यापार समझौता पर हस्ताक्षर',
        'முக்கிய பொருளாதாரங்களுக்கிடையே சர்வதேச வాణிப ஒப்பந்தம் கையெழுத்தானது',
        'ప్రధాన ఆర్థిక వ్యవస్థల మధ్య అంతర్జాతీయ వాణిజ్య ఒప్పందం సంతకం చేయబడింది',
        'एक व्यापक व्यापार समझौता आर्थिक सहयोग बढ़ाने और टैरिफ कम करने का वादा करता है।',
        'ஒரு விரிவான வாணிப ஒப்பந்தம் பொருளாதார ஒத்துழைப்பை அதிகரிக்கவும் கட்டணங்களை குறைக்கவும் வாக்குறுதி அளிக்கிறது.',
        'ఒక సమగ్ర వాణిజ్య ఒప్పందం ఆర్థిక సహకారాన్ని పెంచడానికి మరియు సుంకాలను తగ్గించడానికి వాగ్దానం చేస్తుంది.',
        'राजनीति', 'அரசியல்', 'రాజకీయాలు',
      ),
    ),
    Article(
      id: '5',
      title: 'Defense Secretary Outlines New National Security Strategy',
      content: _loremContent,
      summary: 'The updated strategy focuses on cybersecurity threats and modern defense capabilities.',
      imageUrl: 'assets/images/articles/article_5.jpg',
      categoryId: 'politics',
      categoryName: 'Politics',
      authorName: 'Robert Taylor',
      authorAvatar: 'assets/images/avatars/avatar_7.jpg',
      source: 'CNN',
      publishedAt: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
      readTimeMinutes: 8,
      views: 4200,
      tags: ['Defense', 'Security', 'Cybersecurity'],
      translations: ArticleTranslations.getTranslations(
        'रक्षा सचिव ने नई राष्ट्रीय सुरक्षा रणनीति की रूपरेखा प्रस्तुत की',
        'பாதுகாப்பு செயலர் புதிய தேசிய பாதுகாப்பு உத்தியை கோடிட்டுக் காட்டுகிறார்',
        'రక్షణ కార్యదర్శి కొత్త జాతీయ భద్రతా వ్యూహాన్ని వివరించారు',
        'अद्यतन रणनीति साइबर सुरक्षा खतरों और आधुनिक रक्षा क्षमताओं पर केंद्रित है।',
        'புதுப்பிக்கப்பட்ட உத்தி இணையப் பாதுகாப்பு அச்சுறுத்தல்கள் மற்றும் நவீன பாதுகாப்பு திறன்களில் கவனம் செலுத்துகிறது.',
        'నవీకరించబడిన వ్యూహం సైబర్ భద్రతా ముప్పులు మరియు ఆధునిక రక్షణ సామర్థ్యాలపై దృష్టి పెడుతుంది.',
        'राजनीति', 'அரசியல்', 'రాజకీయాలు',
      ),
    ),

    // SPORTS
    Article(
      id: '6',
      title: 'Champions League Final: Historic Victory Stuns the World',
      content: _loremContent,
      summary: 'An underdog team clinches the Champions League title in a dramatic penalty shootout.',
      imageUrl: 'assets/images/articles/article_6.jpg',
      categoryId: 'sports',
      categoryName: 'Sports',
      authorName: 'Jake Anderson',
      authorAvatar: 'assets/images/avatars/avatar_11.jpg',
      source: 'ESPN',
      publishedAt: DateTime.now().subtract(const Duration(hours: 1)),
      readTimeMinutes: 4,
      views: 24500,
      isBreaking: true,
      tags: ['Football', 'Champions League', 'Final'],
      translations: ArticleTranslations.getTranslations(
        'चैंपियंस लीग फाइनल: ऐतिहासिक जीत ने दुनिया को चौंका दिया',
        'சாம்பியன்ஸ் லீக் இறுதி: வரலாற்று வெற்றி உலகை திகைக்க வைக்கிறது',
        'ఛాంపియన్స్ లీగ్ ఫైనల్: చారిత్రాత్మక విజయం ప్రపంచాన్ని ఆశ్చర్యపరిచింది',
        'एक अंडरडॉग टीम ने नाटकीय पेनल्टी शूटआउट में चैंपियंस लीग का खिताब जीता।',
        'ஒரு பலவீனமான அணி வியத்தகு பெனால்டி ஷூட்அவுட்டில் சாம்பியன்ஸ் லீக் பட்டத்தை வெல்கிறது.',
        'ఒక అండర్‌డాగ్ జట్టు నాటకీయ పెనాల్టీ షూటౌట్‌లో ఛాంపియన్స్ లీగ్ టైటిల్‌ను గెలుచుకుంది.',
        'खेल', 'விளையாட்டு', 'క్రీడలు',
      ),
    ),
    Article(
      id: '7',
      title: 'Olympic Committee Announces New Sports for 2028 Games',
      content: _loremContent,
      summary: 'Five new sports will make their debut at the upcoming Olympic Games in Los Angeles.',
      imageUrl: 'assets/images/articles/article_7.jpg',
      categoryId: 'sports',
      categoryName: 'Sports',
      authorName: 'Lisa Chen',
      authorAvatar: 'assets/images/avatars/avatar_9.jpg',
      source: 'Sports Illustrated',
      publishedAt: DateTime.now().subtract(const Duration(hours: 6)),
      readTimeMinutes: 5,
      views: 15600,
      tags: ['Olympics', 'Sports', '2028'],
      translations: ArticleTranslations.getTranslations(
        'ओलंपिक समिति ने 2028 खेलों के लिए नए खेलों की घोषणा की',
        'ஒலிம்பிக் குழு 2028 விளையாட்டுகளுக்கான புதிய விளையாட்டுகளை அறிவிக்கிறது',
        'ఒలింపిక్ కమిటీ 2028 క్రీడల కోసం కొత్త క్రీడలను ప్రకటించింది',
        'लॉस एंजिल्स में आगामी ओलंपिक खेलों में पांच नए खेल पदार्पण करेंगे।',
        'லாஸ் ஏஞ்சல்ஸில் வரவிருக்கும் ஒலிம்பிக் விளையாட்டுகளில் ஐந்து புதிய விளையாட்டுகள் தோன்றும்.',
        'లాస్ ఏంజిల్స్‌లో రాబోయే ఒలింపిక్ క్రీడలలో ఐదు కొత్త క్రీడలు అవతరించనున్నాయి.',
        'खेल', 'விளையாட்டு', 'క్రీడలు',
      ),
    ),
    Article(
      id: '8',
      title: 'Tennis Star Breaks Grand Slam Record in Melbourne',
      content: _loremContent,
      summary: 'A remarkable performance sees the world number one secure their 25th Grand Slam title.',
      imageUrl: 'assets/images/articles/article_8.jpg',
      categoryId: 'sports',
      categoryName: 'Sports',
      authorName: 'Tom Mitchell',
      authorAvatar: 'assets/images/avatars/avatar_12.jpg',
      source: 'Sky Sports',
      publishedAt: DateTime.now().subtract(const Duration(hours: 10)),
      readTimeMinutes: 3,
      views: 11200,
      tags: ['Tennis', 'Grand Slam', 'Record'],
      translations: ArticleTranslations.getTranslations(
        'टेनिस स्टार ने मेलबर्न में ग्रैंड स्लैम रिकॉर्ड तोड़ा',
        'டென்னிஸ் நட்சத்திரம் மெல்போர்னில் கிராண்ட்ஸ்லாம் சாதனையை முறியடிக்கிறது',
        'టెన్నిస్ స్టార్ మెల్బోర్న్‌లో గ్రాండ్ స్లామ్ రికార్డ్‌ను బద్దలు కొట్టారు',
        'एक उल्लेखनीय प्रदर्शन में विश्व नंबर एक ने अपना 25वां ग्रैंड स्लैम खिताब हासिल किया।',
        'ஒரு குறிப்பிடத்தக்க நிகழ்ச்சி உலக நம்பர் ஒன் தங்கள் 25வது கிராண்ட்ஸ்லாம் பட்டத்தை பெறுவதைக் காண்கிறது.',
        'ఒక గుర్తింపు పొందిన ప్రదర్శనలో ప్రపంచ నంబర్ వన్ తమ 25వ గ్రాండ్ స్లామ్ టైటిల్‌ను సాధించారు.',
        'खेल', 'விளையாட்டு', 'క్రీడలు',
      ),
    ),
    Article(
      id: '9',
      title: 'NBA Draft Prospects: Top 10 Players to Watch This Season',
      content: _loremContent,
      summary: 'Scouting experts reveal the most promising young talents heading into the NBA draft.',
      imageUrl: 'assets/images/articles/article_9.jpg',
      categoryId: 'sports',
      categoryName: 'Sports',
      authorName: 'Chris Johnson',
      authorAvatar: 'assets/images/avatars/avatar_15.jpg',
      source: 'Bleacher Report',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      readTimeMinutes: 6,
      views: 9800,
      tags: ['NBA', 'Draft', 'Basketball'],
      translations: ArticleTranslations.getTranslations(
        'NBA ड्राफ्ट संभावनाएं: इस सीज़न देखने के लिए शीर्ष 10 खिलाड़ी',
        'NBA வரைவு வாய்ப்புகள்: இந்த சீசனில் பார்க்க வேண்டிய முதல் 10 வீரர்கள்',
        'NBA డ్రాఫ్ట్ అవకాశాలు: ఈ సీజన్ వీక్షించాల్సిన టాప్ 10 ఆటగాళ్ళు',
        'स्काउटिंग विशेषज्ञ NBA ड्राफ्ट में सबसे आशाजनक युवा प्रतिभाओं का खुलासा करते हैं।',
        'ஸ்கவுட்டிங் நிபுணர்கள் NBA வரைவுக்குள் செல்லும் மிக நம்பிக்கைக்குரிய இளம் திறமைகளை வெளிப்படுத்துகின்றனர்.',
        'స్కౌటింగ్ నిపుణులు NBA డ్రాఫ్ట్‌లోకి వెళ్తున్న అత్యంత ఆశాజనకమైన యువ ప్రతిభలను వెల్లడిస్తారు.',
        'खेल', 'விளையாட்டு', 'క్రీడలు',
      ),
    ),
    Article(
      id: '10',
      title: 'Formula 1: New Regulations Promise Closer Racing in 2026',
      content: _loremContent,
      summary: 'Revolutionary aerodynamic rules and power unit changes aim to level the playing field.',
      imageUrl: 'assets/images/articles/article_10.jpg',
      categoryId: 'sports',
      categoryName: 'Sports',
      authorName: 'Maria Garcia',
      authorAvatar: 'assets/images/avatars/avatar_16.jpg',
      source: 'Motorsport.com',
      publishedAt: DateTime.now().subtract(const Duration(days: 2)),
      readTimeMinutes: 7,
      views: 7500,
      tags: ['F1', 'Racing', 'Regulations'],
      translations: ArticleTranslations.getTranslations(
        'फॉर्मूला 1: नए नियम 2026 में करीबी रेसिंग का वादा करते हैं',
        'ஃபார்முலா 1: புதிய விதிகள் 2026 இல் நெருக்கமான பந்தயத்தை வாக்குறுதி அளிக்கின்றன',
        'ఫార్ములా 1: కొత్త నిబంధనలు 2026లో దగ్గరి రేసింగ్‌ను వాగ్దానం చేస్తున్నాయి',
        'क्रांतिकारी एयरोडायनामिक नियम और पावर यूनिट परिवर्तन खेल के मैदान को समतल करने का लक्ष्य रखते हैं।',
        'புரட்சிகர ஏரோடைனமிக் விதிகள் மற்றும் சக்தி அலகு மாற்றங்கள் விளையாட்டு களத்தை சமன் செய்வதை நோக்கமாகக் கொண்டுள்ளன.',
        'విప్లవాత్మక ఏరోడైనమిక్ నియమాలు మరియు పవర్ యూనిట్ మార్పులు ఆట మైదానాన్ని సమం చేయడం లక్ష్యంగా పెట్టుకున్నాయి.',
        'खेल', 'விளையாட்டு', 'క్రీడలు',
      ),
    ),

    // TECHNOLOGY
    Article(
      id: '11',
      title: 'AI Breakthrough: New Model Achieves Human-Level Reasoning',
      content: _loremContent,
      summary: 'Researchers develop an AI system that demonstrates unprecedented reasoning capabilities across complex tasks.',
      imageUrl: 'assets/images/articles/article_11.jpg',
      categoryId: 'tech',
      categoryName: 'Technology',
      authorName: 'Alex Rivera',
      authorAvatar: 'assets/images/avatars/avatar_20.jpg',
      source: 'TechCrunch',
      publishedAt: DateTime.now().subtract(const Duration(hours: 3)),
      readTimeMinutes: 6,
      views: 31200,
      isBreaking: true,
      tags: ['AI', 'Machine Learning', 'Research'],
      translations: ArticleTranslations.getTranslations(
        'AI सफलता: नया मॉडल मानव-स्तरीय तर्क प्राप्त करता है',
        'AI முன்னேற்றம்: புதிய மாதிரி மனித-நிலை நியாயத்தை அடைகிறது',
        'AI పురోగతి: కొత్త మోడల్ మానవ-స్థాయి తార్కికతను సాధిస్తుంది',
        'शोधकर्ता एक AI प्रणाली विकसित करते हैं जो जटिल कार्यों में अभूतपूर्व तर्क क्षमता प्रदर्शित करती है।',
        'ஆய்வாளர்கள் சிக்கலான பணிகளில் முன்னெப்போதும் இல்லாத நியாய திறன்களை வெளிப்படுத்தும் ஒரு AI அமைப்பை உருவாக்குகின்றனர்.',
        'పరిశోధకులు సంక్లిష్ట పనులలో అపూర్వమైన తార్కిక సామర్థ్యాలను ప్రదర్శించే AI వ్యవస్థను అభివృద్ధి చేశారు.',
        'प्रौद्योगिकी', 'தொழில்நுட்பம்', 'సాంకేతికత',
      ),
    ),
    Article(
      id: '12',
      title: 'Apple Unveils Revolutionary Mixed Reality Headset',
      content: _loremContent,
      summary: 'The tech giant reveals its next-generation spatial computing device with stunning capabilities.',
      imageUrl: 'assets/images/articles/article_12.jpg',
      categoryId: 'tech',
      categoryName: 'Technology',
      authorName: 'Jennifer Park',
      authorAvatar: 'assets/images/avatars/avatar_21.jpg',
      source: 'The Verge',
      publishedAt: DateTime.now().subtract(const Duration(hours: 7)),
      readTimeMinutes: 8,
      views: 28500,
      tags: ['Apple', 'VR', 'AR', 'Mixed Reality'],
      translations: ArticleTranslations.getTranslations(
        'Apple ने क्रांतिकारी मिक्स्ड रियलिटी हेडसेट का अनावरण किया',
        'Apple புரட்சிகர கலப்பு யதார்த்த தலைக்கவசத்தை வெளிப்படுத்துகிறது',
        'Apple విప్లవాత్మక మిక్స్‌డ్ రియాలిటీ హెడ్‌సెట్‌ను ఆవిష్కరించింది',
        'तकनीकी दिग्गज अद्भुत क्षमताओं के साथ अपने अगली पीढ़ी के स्थानिक कंप्यूटिंग उपकरण का खुलासा करता है।',
        'தொழில்நுட்ப அரக்கன் அதிசயமான திறன்களுடன் அதன் அடுத்த தலைமுறை இடஞ்சார் கணினி சாதனத்தை வெளிப்படுத்துகிறது.',
        'టెక్ దిగ్గజం అద్భుతమైన సామర్థ్యాలతో తన తదుపరి తరం స్పేషియల్ కంప్యూటింగ్ పరికరాన్ని వెల్లడిస్తుంది.',
        'प्रौद्योगिकी', 'தொழில்நுட்பம்', 'సాంకేతికత',
      ),
    ),
    Article(
      id: '13',
      title: 'Quantum Computing Milestone: 1000 Qubit Processor Achieved',
      content: _loremContent,
      summary: 'A major quantum computing company achieves a significant milestone in processor development.',
      imageUrl: 'assets/images/articles/article_13.jpg',
      categoryId: 'tech',
      categoryName: 'Technology',
      authorName: 'David Kim',
      authorAvatar: 'assets/images/avatars/avatar_22.jpg',
      source: 'Wired',
      publishedAt: DateTime.now().subtract(const Duration(hours: 12)),
      readTimeMinutes: 5,
      views: 19800,
      tags: ['Quantum', 'Computing', 'Processor'],
      translations: ArticleTranslations.getTranslations(
        'क्वांटम कंप्यूटिंग मील का पत्थर: 1000 क्यूबिट प्रोसेसर हासिल किया',
        'குவாண்டம் கணினி மைல்கல்: 1000 குபிட் செயலி அடையப்பட்டது',
        'క్వాంటం కంప్యూటింగ్ మైలురాయి: 1000 క్యూబిట్ ప్రాసెసర్ సాధించబడింది',
        'एक प्रमुख क्वांटम कंप्यूटिंग कंपनी प्रोसेसर विकास में एक महत्वपूर्ण मील का पत्थर हासिल करती है।',
        'ஒரு முக்கிய குவாண்டம் கணினி நிறுவனம் செயலி மேம்பாட்டில் ஒரு குறிப்பிடத்தக்க மைல்கல்லை அடைகிறது.',
        'ఒక ప్రధాన క్వాంటం కంప్యూటింగ్ కంపెనీ ప్రాసెసర్ అభివృద్ధిలో ఒక ముఖ్యమైన మైలురాయిని సాధించింది.',
        'प्रौद्योगिकी', 'தொழில்நுட்பம்', 'సాంకేతికత',
      ),
    ),
    Article(
      id: '14',
      title: 'SpaceX Successfully Tests Starship for Mars Mission',
      content: _loremContent,
      summary: 'The latest Starship test brings humanity one step closer to becoming a multi-planetary species.',
      imageUrl: 'assets/images/articles/article_14.jpg',
      categoryId: 'tech',
      categoryName: 'Technology',
      authorName: 'Rachel Adams',
      authorAvatar: 'assets/images/avatars/avatar_23.jpg',
      source: 'Space.com',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      readTimeMinutes: 4,
      views: 22100,
      tags: ['SpaceX', 'Mars', 'Space'],
      translations: ArticleTranslations.getTranslations(
        'SpaceX ने मंगल मिशन के लिए स्टारशिप का सफलतापूर्वक परीक्षण किया',
        'SpaceX செவ்வாய் பயணத்திற்காக ஸ்டார்ஷிப் வெற்றிகரமாக சோதிக்கிறது',
        'SpaceX మార్స్ మిషన్ కోసం స్టార్‌షిప్‌ను విజయవంతంగా పరీక్షించింది',
        'नवीनतम स्टारशिप परीक्षण मानवता को बहु-ग्रहीय प्रजाति बनने के एक कदम करीब लाता है।',
        'சமீபத்திய ஸ்டார்ஷிப் சோதனை மனிதகுலத்தை பல-கிரக இனமாக மாறுவதற்கு ஒரு படி அருகில் கொண்டு வருகிறது.',
        'తాజా స్టార్‌షిప్ పరీక్ష మానవాళిని బహుళ-గ్రహ జాతిగా మారడానికి ఒక అడుగు దగ్గర తెస్తుంది.',
        'प्रौद्योगिकी', 'தொழில்நுட்பம்', 'సాంకేతికత',
      ),
    ),
    Article(
      id: '15',
      title: 'Electric Vehicle Sales Surge 150% in Record-Breaking Quarter',
      content: _loremContent,
      summary: 'Global EV adoption accelerates as new models and charging infrastructure expand rapidly.',
      imageUrl: 'assets/images/articles/article_15.jpg',
      categoryId: 'tech',
      categoryName: 'Technology',
      authorName: 'Mark Stevens',
      authorAvatar: 'assets/images/avatars/avatar_25.jpg',
      source: 'Forbes',
      publishedAt: DateTime.now().subtract(const Duration(days: 2)),
      readTimeMinutes: 5,
      views: 14200,
      tags: ['EV', 'Electric', 'Auto'],
      translations: ArticleTranslations.getTranslations(
        'इलेक्ट्रिक वाहन की बिक्री रिकॉर्ड तोड़ तिमाही में 150% बढ़ी',
        'மின்சார வாகன விற்பனை சாதனை முறியடிக்கும் காலாண்டில் 150% அதிகரிக்கிறது',
        'ఎలక్ట్రిక్ వాహన విక్రయాలు రికార్డు బద్దలు కొట్టే త్రైమాసికంలో 150% పెరిగాయి',
        'नए मॉडल और चार्जिंग इंफ्रास्ट्रक्चर तेजी से विस्तार करने के कारण वैश्विक EV अपनाना तेज हो गया है।',
        'புதிய மாடல்கள் மற்றும் சார்ஜிங் உள்கட்டமைப்பு வேகமாக விரிவடைவதால் உலகளாவிய EV ஏற்பு துரிதப்படுத்துகிறது.',
        'కొత్త మోడల్స్ మరియు ఛార్జింగ్ మౌలిక సదుపాయాలు వేగంగా విస్తరిస్తున్నందున ప్రపంచవ్యాప్త EV స్వీకరణ వేగవంతమవుతుంది.',
        'प्रौद्योगिकी', 'தொழில்நுட்பம்', 'సాంకేతికత',
      ),
    ),

    // ENTERTAINMENT
    Article(
      id: '16',
      title: 'Oscar Nominations 2026: Surprises and Snubs Revealed',
      content: _loremContent,
      summary: 'The Academy announces this year\'s nominations with several unexpected inclusions and notable omissions.',
      imageUrl: 'assets/images/articles/article_16.jpg',
      categoryId: 'entertainment',
      categoryName: 'Entertainment',
      authorName: 'Sophie Martinez',
      authorAvatar: 'assets/images/avatars/avatar_30.jpg',
      source: 'Variety',
      publishedAt: DateTime.now().subtract(const Duration(hours: 4)),
      readTimeMinutes: 5,
      views: 18700,
      isBreaking: true,
      tags: ['Oscars', 'Movies', 'Awards'],
      translations: ArticleTranslations.getTranslations(
        'ऑस्कर नामांकन 2026: आश्चर्य और स्नब का खुलासा',
        'ஆஸ்கார் பரிந்துரைகள் 2026: ஆச்சரியங்கள் மற்றும் புறக்கணிப்புகள் வெளிப்படுத்தப்பட்டன',
        'ఆస్కార్ నామినేషన్స్ 2026: ఆశ్చర్యాలు మరియు స్నబ్‌లు వెల్లడయ్యాయి',
        'अकादमी इस वर्ष के नामांकन की घोषणा करती है जिसमें कई अप्रत्याशित समावेश और उल्लेखनीय चूक हैं।',
        'அகாடமி இந்த ஆண்டு பல எதிர்பாராத சேர்க்கைகள் மற்றும் குறிப்பிடத்தக்க தவறுகளுடன் பரிந்துரைகளை அறிவிக்கிறது.',
        'అకాడమీ ఈ సంవత్సరం అనేక ఊహించని చేర్పులు మరియు ముఖ్యమైన విస్మరణలతో నామినేషన్లను ప్రకటించింది.',
        'मनोरंजन', 'பொழுதுபோக்கு', 'వినోదం',
      ),
    ),
    Article(
      id: '17',
      title: 'Streaming Wars: Netflix Launches Revolutionary Interactive Series',
      content: _loremContent,
      summary: 'Netflix debuts a groundbreaking interactive series that lets viewers shape the storyline in real-time.',
      imageUrl: 'assets/images/articles/article_17.jpg',
      categoryId: 'entertainment',
      categoryName: 'Entertainment',
      authorName: 'James Lee',
      authorAvatar: 'assets/images/avatars/avatar_31.jpg',
      source: 'Hollywood Reporter',
      publishedAt: DateTime.now().subtract(const Duration(hours: 9)),
      readTimeMinutes: 4,
      views: 15300,
      tags: ['Netflix', 'Streaming', 'Interactive'],
      translations: ArticleTranslations.getTranslations(
        'स्ट्रीमिंग वॉर्स: Netflix ने क्रांतिकारी इंटरैक्टिव सीरीज़ लॉन्च की',
        'ஸ்ட்ரீமிங் போர்கள்: Netflix புரட்சிகர ஊடாடும் தொடரை அறிமுகப்படுத்துகிறது',
        'స్ట్రీమింగ్ వార్స్: Netflix విప్లవాత్మక ఇంటరాక్టివ్ సిరీస్‌ను లాంచ్ చేసింది',
        'Netflix एक अभूतपूर्व इंटरैक्टिव सीरीज़ शुरू करता है जो दर्शकों को वास्तविक समय में कहानी को आकार देने देता है।',
        'Netflix பார்வையாளர்களை நேரடியாக கதைக்களத்தை வடிவமைக்க அனுமதிக்கும் ஒரு திறப்பு ஊடாடும் தொடரை அனுமதிக்கிறது.',
        'Netflix వీక్షకులను నిజ-సమయంలో కథాంశాన్ని రూపొందించడానికి అనుమతించే ఒక కొత్త ఇంటరాక్టివ్ సిరీస్‌ను ప్రారంభించింది.',
        'मनोरंजन', 'பொழுதுபோக்கு', 'వినోదం',
      ),
    ),
    Article(
      id: '18',
      title: 'Global Music Festival Announces Star-Studded 2026 Lineup',
      content: _loremContent,
      summary: 'The world\'s biggest music festival reveals a record-breaking lineup featuring top artists.',
      imageUrl: 'assets/images/articles/article_18.jpg',
      categoryId: 'entertainment',
      categoryName: 'Entertainment',
      authorName: 'Nicole White',
      authorAvatar: 'assets/images/avatars/avatar_32.jpg',
      source: 'Billboard',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      readTimeMinutes: 3,
      views: 12100,
      tags: ['Music', 'Festival', 'Concert'],
      translations: ArticleTranslations.getTranslations(
        'वैश्विक संगीत महोत्सव ने स्टार-स्टडेड 2026 लाइनअप की घोषणा की',
        'உலகளாவிய இசை விழா நட்சத்திரங்கள் நிறைந்த 2026 அணியை அறிவிக்கிறது',
        'గ్లోబల్ మ్యూజిక్ ఫెస్టివల్ నక్షత్రాలతో కూడిన 2026 లైనప్‌ను ప్రకటించింది',
        'दुनिया का सबसे बड़ा संगीत महोत्सव शीर्ष कलाकारों को प्रदर्शित करने वाली एक रिकॉर्ड-ब्रेकिंग लाइनअप का खुलासा करता है।',
        'உலகின் மிகப்பெரிய இசை விழா முதன்மை கலைஞர்களை கொண்ட ஒரு சாதனை முறியடிக்கும் அணியை வெளிப்படுத்துகிறது.',
        'ప్రపంచంలోని అతిపెద్ద సంగీత ఉత్సవం టాప్ ఆర్టిస్టులను కలిగి ఉన్న రికార్డు బద్దలు కొట్టే లైనప్‌ను వెల్లడించింది.',
        'मनोरंजन', 'பொழுதுபோக்கு', 'వినోదం',
      ),
    ),
    Article(
      id: '19',
      title: 'Video Game Industry Sets New Revenue Record in 2025',
      content: _loremContent,
      summary: 'The gaming industry surpasses \$200 billion in annual revenue for the first time.',
      imageUrl: 'assets/images/articles/article_19.jpg',
      categoryId: 'entertainment',
      categoryName: 'Entertainment',
      authorName: 'Ryan Cooper',
      authorAvatar: 'assets/images/avatars/avatar_33.jpg',
      source: 'IGN',
      publishedAt: DateTime.now().subtract(const Duration(days: 2)),
      readTimeMinutes: 6,
      views: 9400,
      tags: ['Gaming', 'Revenue', 'Industry'],
      translations: ArticleTranslations.getTranslations(
        'वीडियो गेम उद्योग ने 2025 में नया राजस्व रिकॉर्ड स्थापित किया',
        'வீடியோ விளையாட்டு தொழில் 2025 இல் புதிய வருவாய் சாதனையை அமைக்கிறது',
        'వీడియో గేమ్ ఇండస్ట్రీ 2025లో కొత్త రాబడి రికార్డును నెలకొల్పింది',
        'गेमिंग उद्योग पहली बार वार्षिक राजस्व में \$200 बिलियन से अधिक हो गया है।',
        'விளையாட்டு தொழில் முதல் முறையாக வருடாந்திர வருவாயில் \$200 பில்லியனை தாண்டுகிறது.',
        'గేమింగ్ పరిశ్రమ మొదటిసారిగా వార్షిక రాబడిలో \$200 బిలియన్లను అధిగమించింది.',
        'मनोरंजन', 'பொழுதுபோக்கு', 'వినోదం',
      ),
    ),

    // BUSINESS
    Article(
      id: '20',
      title: 'Wall Street Reaches All-Time High Amid Tech Rally',
      content: _loremContent,
      summary: 'Major stock indexes hit record levels driven by exceptional tech sector performance.',
      imageUrl: 'assets/images/articles/article_20.jpg',
      categoryId: 'business',
      categoryName: 'Business',
      authorName: 'Patricia Wong',
      authorAvatar: 'assets/images/avatars/avatar_40.jpg',
      source: 'Wall Street Journal',
      publishedAt: DateTime.now().subtract(const Duration(hours: 2)),
      readTimeMinutes: 5,
      views: 21300,
      tags: ['Stocks', 'Wall Street', 'Markets'],
      translations: ArticleTranslations.getTranslations(
        'वॉल स्ट्रीट टेक रैली के बीच सर्वकालिक उच्चतम स्तर पर पहुंचा',
        'வால் ஸ்ட்ரீட் தொழில்நுட்ப ஏற்றத்தின் மத்தியில் அனைத்து கால உயரத்தை அடைகிறது',
        'వాల్ స్ట్రీట్ టెక్ ర్యాలీ మధ్య ఆల్-టైమ్ గరిష్టాన్ని చేరుకుంది',
        'प्रमुख स्टॉक इंडेक्स असाधारण तकनीकी सेक्टर प्रदर्शन द्वारा संचालित रिकॉर्ड स्तर पर पहुंचे।',
        'முக்கிய பங்கு குறியீடுகள் விதிவிலக்கான தொழில்நுட்ப துறை செயல்திறனால் இயக்கப்படும் சாதனை நிலைகளை எட்டுகின்றன.',
        'ప్రధాన స్టాక్ ఇండెక్స్‌లు అసాధారణమైన టెక్ రంగ పనితీరుతో రికార్డు స్థాయిలను తాకాయి.',
        'व्यापार', 'வணிகம்', 'వ్యాపారం',
      ),
    ),
    Article(
      id: '21',
      title: 'Startup Ecosystem Thrives: Record VC Funding in Q1 2026',
      content: _loremContent,
      summary: 'Venture capital investment reaches new heights with AI and biotech startups leading the charge.',
      imageUrl: 'assets/images/articles/article_21.jpg',
      categoryId: 'business',
      categoryName: 'Business',
      authorName: 'Daniel Foster',
      authorAvatar: 'assets/images/avatars/avatar_41.jpg',
      source: 'Financial Times',
      publishedAt: DateTime.now().subtract(const Duration(hours: 11)),
      readTimeMinutes: 7,
      views: 13600,
      tags: ['Startup', 'VC', 'Funding'],
      translations: ArticleTranslations.getTranslations(
        'स्टार्टअप इकोसिस्टम फलता-फूलता है: Q1 2026 में रिकॉर्ड VC फंडिंग',
        'ஸ்டார்ட்அப் சூழல் செழிக்கிறது: Q1 2026 இல் சாதனை VC நிதி',
        'స్టార్టప్ ఎకోసిస్టమ్ అభివృద్ధి చెందుతోంది: Q1 2026లో రికార్డు VC ఫండింగ్',
        'AI और बायोटेक स्टार्टअप के नेतृत्व में उद्यम पूंजी निवेश नई ऊंचाइयों तक पहुंचता है।',
        'AI மற்றும் பயோடெக் ஸ்டார்ட்அப்கள் வழிநடத்தும் போது துணிகர மூலதன முதலீடு புதிய உயரங்களை அடைகிறது.',
        'AI మరియు బయోటెక్ స్టార్టప్‌ల నాయకత్వంతో వెంచర్ క్యాపిటల్ పెట్టుబడి కొత్త శిఖరాలను చేరుకుంటుంది.',
        'व्यापार', 'வணிகம்', 'వ్యాపారం',
      ),
    ),
    Article(
      id: '22',
      title: 'Remote Work Revolution: 75% of Companies Adopt Hybrid Models',
      content: _loremContent,
      summary: 'A comprehensive study reveals the permanent shift in workplace dynamics post-pandemic.',
      imageUrl: 'assets/images/articles/article_22.jpg',
      categoryId: 'business',
      categoryName: 'Business',
      authorName: 'Emma Thompson',
      authorAvatar: 'assets/images/avatars/avatar_42.jpg',
      source: 'Business Insider',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      readTimeMinutes: 4,
      views: 10800,
      tags: ['Remote Work', 'Hybrid', 'Workplace'],
      translations: ArticleTranslations.getTranslations(
        'रिमोट वर्क क्रांति: 75% कंपनियों ने हाइब्रिड मॉडल अपनाए',
        'தொலை வேலை புரட்சி: 75% நிறுவனங்கள் கலப்பின மாதிரிகளை ஏற்கின்றன',
        'రిమోట్ వర్క్ విప్లవం: 75% కంపెనీలు హైబ్రిడ్ మోడల్స్‌ను అనుసరిస్తున్నాయి',
        'एक व्यापक अध्ययन महामारी के बाद कार्यस्थल गतिशीलता में स्थायी बदलाव का खुलासा करता है।',
        'ஒரு விரிவான ஆய்வு தொற்றுநோய்க்குப் பின் பணியிட இயக்கவியலில் நிரந்தர மாற்றத்தை வெளிப்படுத்துகிறது.',
        'ఒక సమగ్ర అధ్యయనం మహమ్మారి తర్వాత కార్యాలయ డైనమిక్స్‌లో శాశ్వత మార్పును వెల్లడిస్తుంది.',
        'व्यापार', 'வணிகம்', 'వ్యాపారం',
      ),
    ),
    Article(
      id: '23',
      title: 'Global Supply Chain Overhaul: AI Transforms Logistics Industry',
      content: _loremContent,
      summary: 'Artificial intelligence is revolutionizing supply chain management with predictive analytics.',
      imageUrl: 'assets/images/articles/article_23.jpg',
      categoryId: 'business',
      categoryName: 'Business',
      authorName: 'Kevin O\'Brien',
      authorAvatar: 'assets/images/avatars/avatar_43.jpg',
      source: 'CNBC',
      publishedAt: DateTime.now().subtract(const Duration(days: 2)),
      readTimeMinutes: 6,
      views: 7900,
      tags: ['Supply Chain', 'AI', 'Logistics'],
      translations: ArticleTranslations.getTranslations(
        'वैश्विक आपूर्ति श्रृंखला ओवरहाल: AI लॉजिस्टिक्स उद्योग को बदलता है',
        'உலகளாவிய விநியோக சங்கிலி மறுசீரமைப்பு: AI தளவாட தொழிலை மாற்றுகிறது',
        'గ్లోబల్ సప్లై చైన్ ఓవర్‌హాల్: AI లాజిస్టిక్స్ పరిశ్రమను మారుస్తుంది',
        'कृत्रिम बुद्धिमत्ता भविष्य कहने वाली विश्लेषणात्मकता के साथ आपूर्ति श्रृंखला प्रबंधन में क्रांति ला रही है।',
        'செயற்கை நுண்ணறிவு முன்னறிவிப்பு பகுப்பாய்வுடன் விநியோக சங்கிலி மேலாண்மையில் புரட்சி செய்கிறது.',
        'కృత్రిమ మేధస్సు అంచనా విశ్లేషణలతో సరఫరా గొలుసు నిర్వహణలో విప్లవం చేస్తోంది.',
        'व्यापार', 'வணிகம்', 'వ్యాపారం',
      ),
    ),

    // HEALTH
    Article(
      id: '24',
      title: 'Breakthrough Cancer Treatment Shows 90% Success Rate in Trials',
      content: _loremContent,
      summary: 'A revolutionary immunotherapy treatment demonstrates remarkable results in clinical trials.',
      imageUrl: 'assets/images/articles/article_24.jpg',
      categoryId: 'health',
      categoryName: 'Health',
      authorName: 'Dr. Amanda Brooks',
      authorAvatar: 'assets/images/avatars/avatar_50.jpg',
      source: 'Medical News Today',
      publishedAt: DateTime.now().subtract(const Duration(hours: 3)),
      readTimeMinutes: 6,
      views: 35600,
      isBreaking: true,
      tags: ['Cancer', 'Treatment', 'Immunotherapy'],
      translations: ArticleTranslations.getTranslations(
        'सफलता कैंसर उपचार परीक्षणों में 90% सफलता दर दिखाता है',
        'முன்னேற்ற புற்றுநோய் சிகிச்சை சோதனைகளில் 90% வெற்றி விகிதத்தைக் காட்டுகிறது',
        'బ్రేక్‌థ్రూ క్యాన్సర్ చికిత్స పరీక్షలలో 90% విజయవంతం అవుతుంది',
        'एक क्रांतिकारी इम्यूनोथेरेपी उपचार नैदानिक ​​परीक्षणों में उल्लेखनीय परिणाम प्रदर्शित करता है।',
        'ஒரு புரட்சிகர நோய் எதிர்ப்பு சிகிச்சை மருத்துவ சோதனைகளில் குறிப்பிடத்தக்க முடிவுகளை நிரூபிக்கிறது.',
        'ఒక విప్లవాత్మక ఇమ్యునోథెరపీ చికిత్స క్లినికల్ ట్రయల్స్‌లో అద్భుతమైన ఫలితాలను ప్రదర్శిస్తుంది.',
        'स्वास्थ्य', 'சுகாதாரம்', 'ఆరోగ్యం',
      ),
    ),
    Article(
      id: '25',
      title: 'Mental Health Awareness: New Study Reveals Impact of Social Media',
      content: _loremContent,
      summary: 'Research highlights the complex relationship between social media use and mental health outcomes.',
      imageUrl: 'assets/images/articles/article_25.jpg',
      categoryId: 'health',
      categoryName: 'Health',
      authorName: 'Dr. James Miller',
      authorAvatar: 'assets/images/avatars/avatar_51.jpg',
      source: 'Psychology Today',
      publishedAt: DateTime.now().subtract(const Duration(hours: 8)),
      readTimeMinutes: 5,
      views: 14200,
      tags: ['Mental Health', 'Social Media', 'Study'],
      translations: ArticleTranslations.getTranslations(
        'मानसिक स्वास्थ्य जागरूकता: नया अध्ययन सोशल मीडिया के प्रभाव को प्रकट करता है',
        'மனநல விழிப்புணர்வு: புதிய ஆய்வு சமூக ஊடகத்தின் தாக்கத்தை வெளிப்படுத்துகிறது',
        'మానసిక ఆరోగ్య అవగాహన: కొత్త అధ్యయనం సోషల్ మీడియా ప్రభావాన్ని వెల్లడిస్తుంది',
        'शोध सोशल मीडिया उपयोग और मानसिक स्वास्थ्य परिणामों के बीच जटिल संबंध को उजागर करता है।',
        'ஆராய்ச்சி சமூக ஊடக பயன்பாடு மற்றும் மனநல விளைவுகளுக்கு இடையிலான சிக்கலான உறவை எடுத்துக்காட்டுகிறது.',
        'పరిశోధన సోషల్ మీడియా వినియోగం మరియు మానసిక ఆరోగ్య ఫలితాల మధ్య సంక్లిష్ట సంబంధాన్ని హైలైట్ చేస్తుంది.',
        'स्वास्थ्य', 'சுகாதாரம்', 'ఆరోగ్యం',
      ),
    ),
    Article(
      id: '26',
      title: 'WHO Approves New Universal Flu Vaccine for Global Distribution',
      content: _loremContent,
      summary: 'A next-generation flu vaccine promises broader protection against multiple influenza strains.',
      imageUrl: 'assets/images/articles/article_26.jpg',
      categoryId: 'health',
      categoryName: 'Health',
      authorName: 'Laura Hernandez',
      authorAvatar: 'assets/images/avatars/avatar_52.jpg',
      source: 'WHO News',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      readTimeMinutes: 4,
      views: 11500,
      tags: ['Vaccine', 'WHO', 'Influenza'],
      translations: ArticleTranslations.getTranslations(
        'WHO ने वैश्विक वितरण के लिए नया सार्वभौमिक फ्लू वैक्सीन स्वीकृत किया',
        'WHO உலகளாவிய விநியோகத்திற்கான புதிய உலகளாவிய காய்ச்சல் தடுப்பூசியை அனுமதிக்கிறது',
        'WHO గ్లోబల్ డిస్ట్రిబ్యూషన్ కోసం కొత్త యూనివర్సల్ ఫ్లూ వ్యాక్సిన్‌ను ఆమోదించింది',
        'एक अगली पीढ़ी की फ्लू वैक्सीन कई इन्फ्लूएंजा स्ट्रेन के खिलाफ व्यापक सुरक्षा का वादा करती है।',
        'அடுத்த தலைமுறை காய்ச்சல் தடுப்பூசி பல இன்ஃப்ளூயன்சா வகைகளுக்கு எதிராக பரந்த பாதுகாப்பை வாக்குறுதி அளிக்கிறது.',
        'తదుపరి తరం ఫ్లూ వ్యాక్సిన్ బహుళ ఇన్‌ఫ్లుఎంజా జాతులకు వ్యతిరేకంగా విస్తృత రక్షణను వాగ్దానం చేస్తుంది.',
        'स्वास्थ्य', 'சுகாதாரம்', 'ఆరోగ్యం',
      ),
    ),
    Article(
      id: '27',
      title: 'Nutrition Science Update: Mediterranean Diet Linked to Longevity',
      content: _loremContent,
      summary: 'A decade-long study confirms the significant health benefits of the Mediterranean diet.',
      imageUrl: 'assets/images/articles/article_27.jpg',
      categoryId: 'health',
      categoryName: 'Health',
      authorName: 'Dr. Robert Chen',
      authorAvatar: 'assets/images/avatars/avatar_53.jpg',
      source: 'Health Magazine',
      publishedAt: DateTime.now().subtract(const Duration(days: 2)),
      readTimeMinutes: 5,
      views: 8700,
      tags: ['Nutrition', 'Diet', 'Longevity'],
      translations: ArticleTranslations.getTranslations(
        'पोषण विज्ञान अपडेट: भूमध्यसागरीय आहार दीर्घायु से जुड़ा',
        'ஊட்டச்சத்து அறிவியல் புதுப்பிப்பு: மத்திய தரைக்கடல் உணவு நீண்ட ஆயுளுடன் இணைக்கப்பட்டுள்ளது',
        'పోషకాహార శాస్త్ర నవీకరణ: మెడిటరేనియన్ ఆహారం దీర్ఘాయువుతో ముడిపడి ఉంది',
        'एक दशक के लंबे अध्ययन ने भूमध्यसागरीय आहार के महत्वपूर्ण स्वास्थ्य लाभों की पुष्टि की है।',
        'ஒரு தசாப்த கால ஆய்வு மத்திய தரைக்கடல் உணவின் குறிப்பிடத்தக்க சுகாதார நன்மைகளை உறுதிப்படுத்துகிறது.',
        'ఒక దశాబ్ద-దీర్ఘ అధ్యయనం మెడిటరేనియన్ ఆహారం యొక్క ముఖ్యమైన ఆరోగ్య ప్రయోజనాలను నిర్ధారిస్తుంది.',
        'स्वास्थ्य', 'சுகாதாரம்', 'ఆరోగ్యం',
      ),
    ),

    // SCIENCE
    Article(
      id: '28',
      title: 'NASA Discovers Water on Distant Exoplanet in Habitable Zone',
      content: _loremContent,
      summary: 'The James Webb Space Telescope detects water vapor in the atmosphere of a potentially habitable world.',
      imageUrl: 'assets/images/articles/article_28.jpg',
      categoryId: 'science',
      categoryName: 'Science',
      authorName: 'Dr. Neil Patterson',
      authorAvatar: 'assets/images/avatars/avatar_55.jpg',
      source: 'NASA',
      publishedAt: DateTime.now().subtract(const Duration(hours: 5)),
      readTimeMinutes: 7,
      views: 42000,
      isBreaking: true,
      tags: ['NASA', 'Exoplanet', 'Space'],
      translations: ArticleTranslations.getTranslations(
        'NASA ने रहने योग्य क्षेत्र में दूर के एक्सोप्लैनेट पर पानी की खोज की',
        'NASA வாழக்கூடிய மண்டலத்தில் தொலைதூர எக்ஸோபிளானெட்டில் நீரைக் கண்டுபிடிக்கிறது',
        'NASA నివాసయోగ్య జోన్‌లో సుదూర ఎక్సోప్లానెట్‌లో నీటిని కనుగొన్నది',
        'जेम्स वेब स्पेस टेलीस्कोप संभावित रूप से रहने योग्य दुनिया के वायुमंडल में जल वाष्प का पता लगाता है।',
        'ஜேம்ஸ் வெப் விண்வெளி தொலைநோக்கி சாத்தியமாக வாழக்கூடிய உலகின் வளிமண்டலத்தில் நீர் நீராவியைக் கண்டறிகிறது.',
        'జేమ్స్ వెబ్ స్పేస్ టెలిస్కోప్ సంభావ్యంగా నివసించదగిన ప్రపంచ వాతావరణంలో నీటి ఆవిరిని కనుగొంటుంది.',
        'विज्ञान', 'அறிவியல்', 'సైన్స్',
      ),
    ),
    Article(
      id: '29',
      title: 'Ancient DNA Reveals New Human Species in Southeast Asia',
      content: _loremContent,
      summary: 'Archaeological findings challenge our understanding of human evolution with discovery of new hominin species.',
      imageUrl: 'assets/images/articles/article_29.jpg',
      categoryId: 'science',
      categoryName: 'Science',
      authorName: 'Prof. Diana Shaw',
      authorAvatar: 'assets/images/avatars/avatar_56.jpg',
      source: 'Nature',
      publishedAt: DateTime.now().subtract(const Duration(days: 1)),
      readTimeMinutes: 8,
      views: 19500,
      tags: ['Archaeology', 'DNA', 'Evolution'],
      translations: ArticleTranslations.getTranslations(
        'प्राचीन DNA दक्षिण पूर्व एशिया में नई मानव प्रजाति का खुलासा करता है',
        'பழங்கால DNA தென்கிழக்கு ஆசியாவில் புதிய மனித இனத்தை வெளிப்படுத்துகிறது',
        'ప్రాచీన DNA ఆగ్నేయాసియాలో కొత్త మానవ జాతిని వెల్లడిస్తుంది',
        'पुरातात्विक खोज नई होमिनिन प्रजातियों की खोज के साथ मानव विकास की हमारी समझ को चुनौती देती है।',
        'தொல்லியல் கண்டுபிடிப்புகள் புதிய மனித இன கண்டுபிடிப்புடன் மனித பரிணாம வளர்ச்சி பற்றிய நமது புரிதலை சவால் செய்கின்றன.',
        'పురావస్తు పరిశోధనలు కొత్త హోమినిన్ జాతుల ఆవిష్కరణతో మానవ పరిణామంపై మన అవగాహనను సవాలు చేస్తున్నాయి.',
        'विज्ञान', 'அறிவியல்', 'సైన్స్',
      ),
    ),
    Article(
      id: '30',
      title: 'Deep Sea Exploration Reveals New Ecosystem Near Ocean Floor',
      content: _loremContent,
      summary: 'Marine scientists discover a thriving ecosystem thousands of meters below the ocean surface.',
      imageUrl: 'assets/images/articles/article_30.jpg',
      categoryId: 'science',
      categoryName: 'Science',
      authorName: 'Dr. Ocean Wright',
      authorAvatar: 'assets/images/avatars/avatar_57.jpg',
      source: 'Scientific American',
      publishedAt: DateTime.now().subtract(const Duration(days: 2)),
      readTimeMinutes: 5,
      views: 13800,
      tags: ['Ocean', 'Discovery', 'Marine'],
      translations: ArticleTranslations.getTranslations(
        'गहरे समुद्र की खोज समुद्र तल के पास नए पारिस्थितिकी तंत्र का खुलासा करती है',
        'ஆழ்கடல் ஆய்வு கடல் தளத்திற்கு அருகில் புதிய சூழல் அமைப்பை வெளிப்படுத்துகிறது',
        'డీప్ సీ ఎక్స్‌ప్లోరేషన్ సముద్ర అడుగుభాగానికి సమీపంలో కొత్త పర్యావరణ వ్యవస్థను వెల్లడిస్తుంది',
        'समुद्री वैज्ञानिक समुद्र की सतह से हजारों मीटर नीचे एक संपन्न पारिस्थितिकी तंत्र की खोज करते हैं।',
        'கடல் விஞ்ஞானிகள் கடல் மேற்பரப்புக்கு ஆயிரக்கணக்கான மீட்டர் கீழே ஒரு செழிப்பான சூழல் அமைப்பைக் கண்டுபிடித்துள்ளனர்.',
        'సముద్ర శాస్త్రవేత్తలు సముద్ర ఉపరితలానికి వేలాది మీటర్ల క్రింద అభివృద్ధి చెందుతున్న పర్యావరణ వ్యవస్థను కనుగొన్నారు.',
        'विज्ञान', 'அறிவியல்', 'సైన్స్',
      ),
    ),
  ];

  static final List<Comment> comments = [
    Comment(id: 'c1', articleId: '1', userName: 'Alice Johnson', userAvatar: 'assets/images/avatars/avatar_60.jpg', content: 'This is a great step forward for climate action. We need more leaders to commit to these targets.', createdAt: DateTime.now().subtract(const Duration(hours: 1)), likes: 24),
    Comment(id: 'c2', articleId: '1', userName: 'Bob Williams', userAvatar: 'assets/images/avatars/avatar_61.jpg', content: 'I hope this translates into real action and not just empty promises.', createdAt: DateTime.now().subtract(const Duration(hours: 1, minutes: 30)), likes: 18),
    Comment(id: 'c3', articleId: '1', userName: 'Carol Davis', userAvatar: 'assets/images/avatars/avatar_62.jpg', content: 'Finally some good news! The framework seems comprehensive and achievable.', createdAt: DateTime.now().subtract(const Duration(hours: 2)), likes: 12),
    Comment(id: 'c4', articleId: '6', userName: 'Dan Miller', userAvatar: 'assets/images/avatars/avatar_63.jpg', content: 'What a match! Best Champions League final I\'ve ever watched!', createdAt: DateTime.now().subtract(const Duration(minutes: 30)), likes: 56),
    Comment(id: 'c5', articleId: '6', userName: 'Eve Brown', userAvatar: 'assets/images/avatars/avatar_64.jpg', content: 'The underdog story is absolutely incredible. Pure football magic!', createdAt: DateTime.now().subtract(const Duration(minutes: 45)), likes: 34),
    Comment(id: 'c6', articleId: '11', userName: 'Frank Wilson', userAvatar: 'assets/images/avatars/avatar_65.jpg', content: 'This is both exciting and slightly terrifying. The pace of AI development is incredible.', createdAt: DateTime.now().subtract(const Duration(hours: 2)), likes: 42),
    Comment(id: 'c7', articleId: '11', userName: 'Grace Lee', userAvatar: 'assets/images/avatars/avatar_66.jpg', content: 'As a researcher in the field, I can confirm this is a significant breakthrough.', createdAt: DateTime.now().subtract(const Duration(hours: 2, minutes: 15)), likes: 38),
    Comment(id: 'c8', articleId: '24', userName: 'Henry Taylor', userAvatar: 'assets/images/avatars/avatar_67.jpg', content: 'This gives so much hope to cancer patients worldwide. Science is amazing!', createdAt: DateTime.now().subtract(const Duration(hours: 1)), likes: 67),
    Comment(id: 'c9', articleId: '28', userName: 'Iris Zhang', userAvatar: 'assets/images/avatars/avatar_68.jpg', content: 'Finding water on an exoplanet is a huge milestone. Can\'t wait for more discoveries!', createdAt: DateTime.now().subtract(const Duration(hours: 3)), likes: 51),
    Comment(id: 'c10', articleId: '20', userName: 'Jack Robinson', userAvatar: 'assets/images/avatars/avatar_69.jpg', content: 'The market rally seems sustainable with strong fundamentals backing it.', createdAt: DateTime.now().subtract(const Duration(hours: 1)), likes: 15),
  ];

  static final List<AppUser> users = [
    AppUser(id: 'u1', name: 'John Doe', email: 'john@example.com', avatarUrl: 'assets/images/avatars/avatar_1.jpg', joinedAt: DateTime(2024, 1, 15), articlesRead: 245, bookmarksCount: 32),
    AppUser(id: 'u2', name: 'Jane Smith', email: 'jane@example.com', avatarUrl: 'assets/images/avatars/avatar_5.jpg', joinedAt: DateTime(2024, 3, 22), articlesRead: 189, bookmarksCount: 28),
    AppUser(id: 'u3', name: 'Mike Johnson', email: 'mike@example.com', avatarUrl: 'assets/images/avatars/avatar_9.jpg', joinedAt: DateTime(2024, 5, 10), articlesRead: 156, bookmarksCount: 15),
    AppUser(id: 'u4', name: 'Sarah Williams', email: 'sarah@example.com', avatarUrl: 'assets/images/avatars/avatar_10.jpg', joinedAt: DateTime(2024, 7, 4), articlesRead: 312, bookmarksCount: 45),
    AppUser(id: 'u5', name: 'Chris Brown', email: 'chris@example.com', avatarUrl: 'assets/images/avatars/avatar_12.jpg', joinedAt: DateTime(2024, 8, 19), isBlocked: true, articlesRead: 78, bookmarksCount: 5),
    AppUser(id: 'u6', name: 'Emily Davis', email: 'emily@example.com', avatarUrl: 'assets/images/avatars/avatar_15.jpg', joinedAt: DateTime(2024, 9, 1), articlesRead: 98, bookmarksCount: 12),
    AppUser(id: 'u7', name: 'David Wilson', email: 'david@example.com', avatarUrl: 'assets/images/avatars/avatar_20.jpg', joinedAt: DateTime(2024, 10, 12), articlesRead: 67, bookmarksCount: 8),
    AppUser(id: 'u8', name: 'Lisa Anderson', email: 'lisa@example.com', avatarUrl: 'assets/images/avatars/avatar_21.jpg', joinedAt: DateTime(2025, 1, 5), articlesRead: 134, bookmarksCount: 22),
    AppUser(id: 'admin', name: 'Admin User', email: 'admin@newsportal.com', avatarUrl: 'assets/images/avatars/avatar_70.jpg', joinedAt: DateTime(2023, 6, 1), isAdmin: true, articlesRead: 500, bookmarksCount: 50),
  ];

  static final List<AppNotification> notifications = [
    AppNotification(id: 'n1', title: 'Breaking News', body: 'Global Leaders Summit Addresses Climate Policy Framework', type: 'breaking', createdAt: DateTime.now().subtract(const Duration(hours: 2)), articleId: '1'),
    AppNotification(id: 'n2', title: 'Sports Alert', body: 'Champions League Final: Historic Victory Stuns the World', type: 'breaking', createdAt: DateTime.now().subtract(const Duration(hours: 1)), articleId: '6'),
    AppNotification(id: 'n3', title: 'Tech Update', body: 'AI Breakthrough: New Model Achieves Human-Level Reasoning', type: 'article', createdAt: DateTime.now().subtract(const Duration(hours: 3)), articleId: '11'),
    AppNotification(id: 'n4', title: 'Health News', body: 'Breakthrough Cancer Treatment Shows 90% Success Rate', type: 'breaking', createdAt: DateTime.now().subtract(const Duration(hours: 3)), articleId: '24'),
    AppNotification(id: 'n5', title: 'Science Discovery', body: 'NASA Discovers Water on Distant Exoplanet', type: 'article', createdAt: DateTime.now().subtract(const Duration(hours: 5)), articleId: '28'),
    AppNotification(id: 'n6', title: 'Welcome!', body: 'Welcome to QuickPrepAI News! Customize your news feed preferences.', type: 'system', createdAt: DateTime.now().subtract(const Duration(days: 1))),
    AppNotification(id: 'n7', title: 'Weekly Digest', body: 'Your weekly news digest is ready. Tap to read the top stories.', type: 'system', createdAt: DateTime.now().subtract(const Duration(days: 2)), isRead: true),
    AppNotification(id: 'n8', title: 'New Category', body: 'Science category is now available! Explore the latest discoveries.', type: 'system', createdAt: DateTime.now().subtract(const Duration(days: 3)), isRead: true),
  ];

  static final List<String> trendingTopics = [
    'Climate Change',
    'AI Revolution',
    'Champions League',
    'Space Exploration',
    'Cancer Research',
    'Electric Vehicles',
    'Stock Market',
    'Oscar Nominations',
  ];
}
